yarnPath: .yarn/releases/yarn-3.1.0.cjs
nodeLinker: node-modules
packageExtensions:
  # awaiting fix: https://github.com/facebook/create-react-app/issues/10809
  'eslint-config-react-app@*':
    dependencies:
      eslint-plugin-flowtype: '*'
      babel-eslint: '*'
      '@typescript-eslint/parser': '*'
      '@typescript-eslint/eslint-plugin': '*'
