import pluginReactRefresh from 'eslint-plugin-react-refresh'
import pluginReactHooks from 'eslint-plugin-react-hooks'
import pluginImport from 'eslint-plugin-import'
import globals from 'globals'
import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import js from '@eslint/js'

export default [
  {
    ignores: [
      '**/dist',
      '**/node_modules',
      '**/*.mjs',
      'backend',
      'backend-dev',
      'playwright-report',
      'test-results',
    ],
  },
  js.configs.recommended,
  ...tsPlugin.configs['flat/recommended'],
  ...tsPlugin.configs['flat/stylistic'],
  pluginReactHooks.configs.flat.recommended,
  {
    plugins: {
      'react-refresh': pluginReactRefresh,
      import: pluginImport,
    },

    languageOptions: {
      globals: {
        ...globals.browser,
      },

      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',

      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },

    rules: {
      strict: 0,
      'react/prop-types': 0,
      'react/display-name': 'off',
      'no-console': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // Disable base rule and use TypeScript version
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],

      'no-empty': [
        'error',
        {
          allowEmptyCatch: true,
        },
      ],

      'react/react-in-jsx-scope': 'off',

      'react-refresh/only-export-components': [
        'warn',
        {
          allowConstantExport: true,
        },
      ],

      'import/extensions': [
        'warn',
        'ignorePackages',
        {
          jsx: 'never',
          ts: 'never',
          tsx: 'never',
        },
      ],

      // TypeScript-specific rules
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-non-null-assertion': 'warn',

      // new react-hooks v7 compiler rules: adopted at warn until the
      // existing violations are worked off
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/immutability': 'warn',
    },
  },
  {
    // vendored from the archived react-contextmenu package — pre-existing code style
    files: ['src/modules/react-contextmenu/**'],
    rules: {
      'no-var': 'off',
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      'prefer-const': 'off',
      'no-this-alias': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      'no-useless-assignment': 'off',
      'no-unused-expressions': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/prefer-for-of': 'off',
    },
  },
  {
    // generated by Kanel (see the @generated header) — do not modify manually
    files: ['src/models/**'],
    rules: {
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
]
