// @flow

export default {
    ap: null,
    pop: null,
    tpop: null,
    tpopkontr: null,
    tpopfeldkontr: null,
    tpopfreiwkontr: null,
    tpopkontrzaehl: null,
    tpopmassn: null,
    ziel: null,
    zielber: null,
    erfkrit: null,
    apber: null,
    apberuebersicht: null,
    ber: null,
    idealbiotop: null,
    assozart: null,
    popber: null,
    popmassnber: null,
    tpopber: null,
    tpopmassnber: null,
    apart: null,
    projekt: null,
    beob: null,
    beobprojekt: null,
    adresse: null,
    gemeinde: null,
    user: null,
    __typename: 'NodeLabelFilter'
  }
