// @flow
export default [
  'flaeche',
  'lr_delarze',
  'lr_umgebung_delarze',
  'vegetationstyp',
  'konkurrenz',
  'moosschicht',
  'krautschicht',
  'strauchschicht',
  'baumschicht',
  'boden_typ',
  'boden_kalkgehalt',
  'boden_durchlaessigkeit',
  'boden_humus',
  'boden_naehrstoffgehalt',
  'boden_abtrag',
  'wasserhaushalt',
  'handlungsbedarf',
  'idealbiotop_uebereinstimmung',
]
