// @flow
export default [
  'TPopKontrFlaeche',
  'TPopKontrLeb',
  'TPopKontrLebUmg',
  'TPopKontrVegTyp',
  'TPopKontrKonkurrenz',
  'TPopKontrMoosschicht',
  'TPopKontrKrautschicht',
  'TPopKontrStrauchschicht',
  'TPopKontrBaumschicht',
  'TPopKontrBodenTyp',
  'TPopKontrBodenKalkgehalt',
  'TPopKontrBodenDurchlaessigkeit',
  'TPopKontrBodenHumus',
  'TPopKontrBodenNaehrstoffgehalt',
  'TPopKontrBodenAbtrag',
  'TPopKontrWasserhaushalt',
  'TPopKontrHandlungsbedarf',
  'TPopKontrIdealBiotopUebereinst',
]
