export default [
  {
    table: 'ap',
    parentTable: 'projekt',
    label: 'Arten',
    labelSingular: 'Art',
    idField: 'id',
    parentIdField: 'proj_id',
  },
  {
    table: 'pop',
    parentTable: 'ap',
    label: 'Populationen',
    labelSingular: 'Population',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'tpop',
    parentTable: 'pop',
    label: 'Teil-Populationen',
    labelSingular: 'Teil-Population',
    idField: 'id',
    parentIdField: 'pop_id',
  },
  {
    table: 'tpopkontr',
    parentTable: 'tpop',
    label: 'Kontrollen',
    labelSingular: 'Kontrolle',
    idField: 'id',
    parentIdField: 'tpop_id',
  },
  {
    table: 'tpopfeldkontr',
    parentTable: 'tpop',
    dbTable: 'tpopkontr',
    label: 'Feld-Kontrollen',
    labelSingular: 'Feld-Kontrolle',
    idField: 'id',
    parentIdField: 'tpop_id',
  },
  {
    table: 'tpopfreiwkontr',
    parentTable: 'tpop',
    dbTable: 'tpopkontr',
    label: 'Freiwilligen-Kontrollen',
    labelSingular: 'Freiwilligen-Kontrolle',
    idField: 'id',
    parentIdField: 'tpop_id',
  },
  {
    table: 'tpopkontrzaehl_einheit_werte',
    label: 'Zähl-Einheit-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'tpopkontrzaehl_methode_werte',
    label: 'Zähl-Methode-Werte',
    idField: 'id',
    parentIdField: 'Zähl-Methode-Werte',
    stammdaten: true,
  },
  {
    table: 'tpopkontrzaehl',
    parentTable: 'tpopkontr',
    label: 'Zählungen',
    labelSingular: 'Zählung',
    idField: 'id',
    parentIdField: 'tpopkontr_id',
  },
  {
    table: 'tpopfreiwkontrzaehl',
    parentTable: 'tpopfreiwkontr',
    dbTable: 'tpopkontrzaehl',
    label: 'Zählungen',
    labelSingular: 'Zählung',
    idField: 'id',
    parentIdField: 'tpopkontr_id',
  },
  {
    table: 'tpopfeldkontrzaehl',
    parentTable: 'tpopfeldkontr',
    dbTable: 'tpopkontrzaehl',
    label: 'Zählungen',
    labelSingular: 'Zählung',
    idField: 'id',
    parentIdField: 'tpopkontr_id',
  },
  {
    table: 'tpopmassn',
    parentTable: 'tpop',
    label: 'Massnahmen',
    labelSingular: 'Massnahme',
    idField: 'id',
    parentIdField: 'tpop_id',
  },
  {
    table: 'tpopmassn_typ_werte',
    label: 'Massnahmen-Typ-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'popmassn_erfbeurt_werte',
    label: 'Massnahmen-Erfolgsbeurteilung-Werte',
    idField: 'BeurteilId',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'tpopmassn_erfbeurt_werte',
    label: 'Massnahmen-Erfolgsbeurteilung-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'ziel',
    parentTable: 'ap',
    label: 'AP-Ziele',
    labelSingular: 'AP-Ziel',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'ziel_typ_werte',
    label: 'Ziel-Typ-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'zielber',
    parentTable: 'ziel',
    label: 'Berichte',
    labelSingular: 'Bericht',
    idField: 'id',
    parentIdField: 'ziel_id',
  },
  {
    table: 'erfkrit',
    parentTable: 'ap',
    label: 'AP-Erfolgskriterien',
    labelSingular: 'AP-Erfolgskriterium',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'apber',
    parentTable: 'ap',
    label: 'AP-Berichte',
    labelSingular: 'AP-Bericht',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'apberuebersicht',
    parentTable: 'projekt',
    label: 'AP-Berichte',
    labelSingular: 'AP-Bericht',
    idField: 'id',
    parentIdField: 'proj_id',
  },
  {
    table: 'ber',
    parentTable: 'ap',
    label: 'Berichte',
    labelSingular: 'Bericht',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'idealbiotop',
    parentTable: 'ap',
    label: 'Idealbiotop',
    labelSingular: 'Idealbiotop',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'assozart',
    parentTable: 'ap',
    label: 'assoziierte Arten',
    labelSingular: 'assoziierte Art',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'ekzaehleinheit',
    parentTable: 'ap',
    label: 'EK-Zähleinheiten',
    labelSingular: 'EK-Zähleinheit',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'popber',
    parentTable: 'pop',
    label: 'Kontroll-Berichte',
    labelSingular: 'Kontroll-Bericht',
    idField: 'id',
    parentIdField: 'pop_id',
  },
  {
    table: 'popmassnber',
    parentTable: 'pop',
    label: 'Massnahmen-Berichte',
    labelSingular: 'Massnahmen-Bericht',
    idField: 'id',
    parentIdField: 'pop_id',
  },
  {
    table: 'tpopber',
    parentTable: 'tpop',
    label: 'Kontroll-Berichte',
    labelSingular: 'Kontroll-Bericht',
    idField: 'id',
    parentIdField: 'tpop_id',
  },
  {
    table: 'tpopmassnber',
    parentTable: 'tpop',
    label: 'Massnahmen-Berichte',
    labelSingular: 'Massnahmen-Bericht',
    idField: 'id',
    parentIdField: 'tpop_id',
  },
  {
    table: 'apart',
    parentTable: 'ap',
    label: 'AP-Art',
    idField: 'id',
    parentIdField: 'ap_id',
  },
  {
    table: 'projekt',
    label: 'Projekte',
    labelSingular: 'Projekt',
    idField: 'id',
  },
  {
    table: 'beob',
    label: 'Beobachtung',
    idField: 'id',
    parentIdField: 'art_id',
  },
  {
    table: 'beobNichtZuzuordnen',
    parentTable: 'ap',
    label: 'Beobachtung',
    idField: 'id',
    parentIdField: 'art_id',
  },
  {
    table: 'beobNichtBeurteilt',
    parentTable: 'ap',
    label: 'Beobachtung',
    idField: 'id',
    parentIdField: 'art_id',
  },
  {
    table: 'beobZugeordnet',
    parentTable: 'tpop',
    label: 'Beobachtung',
    idField: 'id',
    parentIdField: 'tpop_id',
  },
  {
    table: 'beobprojekt',
    parentTable: 'projekt',
    label: 'none',
    idField: 'id',
    parentIdField: 'proj_id',
  },
  {
    table: 'ae_eigenschaften',
    label: 'none',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'ap_bearbstand_werte',
    label: 'AP-Bearbeitungsstand-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'ap_umsetzung_werte',
    label: 'AP-Umsetzung-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'adresse',
    label: 'Adresse',
    idField: 'id',
    parentIdField: 'none',
  },
  {
    table: 'tpop_apberrelevant_grund_werte',
    label: 'Grund für AP-Bericht Relevanz',
    idField: 'id',
    parentIdField: 'none',
  },
  {
    table: 'tpopkontrzaehl_einheit_werte',
    label: 'Zähl-Einheit',
    idField: 'id',
    parentIdField: 'none',
  },
  {
    table: 'ap_erfkrit_werte',
    label: 'AP-Erfolgskriterium-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'pop_status_werte',
    label: 'Pop-Status-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'gemeinde',
    label: 'Gemeinde',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'tpop_entwicklung_werte',
    label: 'Entwicklung-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'tpopkontr_idbiotuebereinst_werte',
    label: 'Idealbiotop-Übereinstimmungs-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'beob_quelle_werte',
    label: 'Beob-Quelle-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'ae_lrdelarze',
    label: 'LR-Delarze-Werte',
    idField: 'id',
    parentIdField: 'none',
    stammdaten: true,
  },
  {
    table: 'message',
    label: 'Meldung',
    idField: 'id',
    parentIdField: 'none',
  },
  {
    table: 'user',
    parentTable: 'none',
    label: 'Benutzer',
    labelSingular: 'Benutzer',
    idField: 'id',
    parentIdField: 'none',
  },
  {
    table: 'currentIssue',
    parentTable: 'none',
    label: 'Aktuelle Fehler',
    labelSingular: 'Aktueller Fehler',
    idField: 'id',
    parentIdField: 'none',
  },
]
