# https://hub.docker.com/r/caddy/caddy/dockerfile
# https://github.com/caddyserver/caddy-docker
# https://github.com/caddyserver/caddy-docker#supported-tags-and-respective-dockerfile-links
FROM caddy/caddy:v2.0.0-beta.15-alpine
COPY Caddyfile /etc/caddy/Caddyfile