# https://hub.docker.com/r/caddy/caddy/dockerfile
# https://github.com/caddyserver/caddy-docker
# https://github.com/caddyserver/caddy-docker#supported-tags-and-respective-dockerfile-links
FROM caddy/caddy:2.0.0-alpine
COPY Caddyfile /etc/caddy/Caddyfile