services:
  graphql:
    container_name: apf_graphql
    restart: unless-stopped
    build:
      context: ./graphql
    expose:
      - '5000'
    ports:
      - '5000:5000'
    # this is on linux to connect from docker to localhost
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./.env
    command:
      [
        '--connection',
        '${DATABASE_URL}',
        '--schema',
        'apflora',
        '--append-plugins',
        'postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related,@graphile/postgis,postgraphile-plugin-connection-filter-postgis',
        '--jwt-token-identifier',
        'auth.jwt_token',
        '--default-role',
        'postgres',
        '--jwt-secret',
        '${JWT_SECRET}',
        '--body-size-limit',
        '2MB',
        '--cors',
        '--disable-query-log',
        '--enable-query-batching',
        '--retry-on-init-fail',
        '--enhance-graphiql',
      ]
