export const overlays = [
  { label: 'Markierungen', value: 'Markierungen' },
  { label: 'Detailpläne', value: 'Detailplaene' },
  {
    label: 'Massnahmenpläne der aktiven Art, Flächen',
    value: 'MassnahmenFlaechen',
  },
  {
    label: 'Massnahmenpläne der aktiven Art, Linien',
    value: 'MassnahmenLinien',
  },
  {
    label: 'Massnahmenpläne der aktiven Art, Punkte',
    value: 'MassnahmenPunkte',
  },
  { label: 'NS-Gebiete Betreuung', value: 'Betreuungsgebiete' },
  { label: 'ZH Übersichtsplan', value: 'ZhUep' },
  {
    label: 'Gemeinden',
    value: 'Gemeinden',
    // wmsUrl: '//wms.geo.admin.ch',
    // wmsVersion: '1.3.0',
    // wmsCrs: 'EPSG:4326',
    // wmsLayers: 'gemeinden',
    // wmsQueryLayers: 'ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill',
    // wmsInfoFormat: 'text/plain',
  },
  {
    label: 'Schutzanordnungen',
    value: 'ZhSvo',
    name: 'ZhSvo',
    wmsUrl: '//wms.zh.ch/FnsSchutzanordnungenZH',
    wmsVersion: '1.3.0',
    wmsCrs: 'EPSG:4326',
    wmsLayers:
      'objekt-umriss,schutzzonen-farbig,zonen-nach-schutzkategorien,ueberlagernde-schutzzonen-naturschutz,schutztyp-naturschutz,ueberlagernde-schutzzonen,schutzzonen-labels,objekt-label',
    wmsQueryLayers: 'objekt-umriss,schutzzonen-farbig',
    wmsInfoFormat: 'application/vnd.ogc.gml',
  },
  {
    label: 'Pflegeplan aktuelles Jahr',
    value: 'ZhPflegeplanAJ',
    name: 'ZhPflegeplanAJ',
    wmsUrl: '//wms.zh.ch/FnsPflegeajZH',
    wmsVersion: '1.3.0',
    wmsCrs: 'EPSG:4326',
    wmsLayers:
      'FnsPflegeajZH,pflegeplan_uebersicht,pfpl-aktuell,ueberlagerung1-aktuell,ueberlagerung2-aktuell',
    wmsQueryLayers:
      'FnsPflegeajZH,pflegeplan_uebersicht,pfpl-aktuell,ueberlagerung1-aktuell,ueberlagerung2-aktuell',
    wmsInfoFormat: 'application/vnd.ogc.gml',
  },
  {
    label: 'Pflegeplan vergangenes Jahr',
    value: 'ZhPflegeplanVJ',
    name: 'ZhPflegeplanVJ',
    wmsUrl: '//wms.zh.ch/FnsPflegevjZH',
    wmsVersion: '1.3.0',
    wmsCrs: 'EPSG:4326',
    wmsLayers:
      'FnsPflegevjZH,teilflaechenumrisse-vergangen,pfpl-vergangen,ueberlagerung1-vergangen,ueberlagerung2-vergangen,umgeb-vergangen,pfpl-label-vergangen',
    wmsQueryLayers: 'FnsPflegevjZH,teilflaechenumrisse-vergangen',
    wmsInfoFormat: 'application/vnd.ogc.gml',
  },
  {
    label: 'Pflegeplan vor-vergangenes Jahr',
    value: 'ZhPflegeplanVVJ',
    name: 'ZhPflegeplanVVJ',
    wmsUrl: '//wms.zh.ch/FnsPflegevvjZH',
    wmsVersion: '1.3.0',
    wmsCrs: 'EPSG:4326',
    wmsLayers:
      'FnsPflegevvjZH,teilflaechenumrisse-vor-vergangenes,pfpl-vor-vergangenes,ueberlagerung1-vor-vergangenes,ueberlagerung2-vor-vergangenes,umgeb-vor-vergangenes,pfpl-label-vor-vergangenes',
    wmsQueryLayers: 'FnsPflegevvjZH,teilflaechenumrisse-vor-vergangenes',
    wmsInfoFormat: 'application/vnd.ogc.gml',
  },
  {
    label: 'Lebensraum- und Vegetationskartierungen',
    value: 'ZhLrVegKartierungen',
    name: 'ZhLrVegKartierungen',
    wmsUrl: '//wms.zh.ch/FnsLRKZH',
    wmsVersion: '1.3.0',
    wmsCrs: 'EPSG:4326',
    wmsLayers:
      'FnsLRKZH,uebersicht,wiesen12,trocken11,trocken01-10,trocken00,moore,feucht-11,feucht-01-10,feucht-81-00,feucht-71-80,feucht-61,auen-93',
    wmsQueryLayers:
      'FnsLRKZH,uebersicht,wiesen12,trocken11,trocken01-10,trocken00,moore,feucht-11,feucht-01-10,feucht-81-00,feucht-71-80,feucht-61,auen-93',
    wmsInfoFormat: 'application/vnd.ogc.gml',
  },
  { label: 'Wälder: lichte', value: 'ZhLichteWaelder' },
  {
    label: 'Wälder: Vegetation',
    value: 'ZhWaelderVegetation',
    name: 'ZhWaelderVegetation',
    // get info works, returns data
    name: 'ZhWaelderVegetation',
    wmsUrl: '//wms.zh.ch/WaldVKWMS',
    wmsVersion: '1.3.0',
    wmsCrs: 'EPSG:4326',
    wmsLayers: 'waldgesellschaften',
    wmsQueryLayers: 'waldgesellschaften',
    wmsInfoFormat: 'application/vnd.ogc.gml',
  },
  {
    label: 'Forstreviere (WMS)',
    value: 'ZhForstreviereWms',
    name: 'ZhForstreviereWms',
    wmsUrl: '//wms.zh.ch/WaldEGZH',
    wmsVersion: '1.3.0',
    wmsCrs: 'EPSG:4326',
    wmsLayers: 'forstreviere',
    wmsQueryLayers: 'forstreviere',
    wmsInfoFormat: 'application/vnd.ogc.gml',
  },
  {
    label: 'Forstreviere. Stand: 2025.04.10',
    value: 'Forstreviere',
  },
]
