// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface cookie_params {
  c: string;
}

/** Return type for cookie */
export type cookie_return_type = string;
