// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface env_var_params {
  v: string;
}

/** Return type for env_var */
export type env_var_return_type = string;
