// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface header_params {
  h: string;
}

/** Return type for header */
export type header_return_type = string;
