// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface jwt_claim_params {
  c: string;
}

/** Return type for jwt_claim */
export type jwt_claim_return_type = string;
