// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface user_name_params {
}

/** Return type for user_name */
export type user_name_return_type = string;
