// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface user_role_params {
}

/** Return type for user_role */
export type user_role_return_type = string;
