// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface beob_extract_absenz_params {
  _beob: unknown;
}

/** Return type for beob_extract_absenz */
export type beob_extract_absenz_return_type = boolean;
