// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface beob_extract_datum_params {
  _beob: unknown;
}

/** Return type for beob_extract_datum */
export type beob_extract_datum_return_type = Date;
