// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface beob_extract_autor_params {
  _beob: unknown;
}

/** Return type for beob_extract_autor */
export type beob_extract_autor_return_type = string;
