// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface beob_extract_art_params {
  _beob: unknown;
}

/** Return type for beob_extract_art */
export type beob_extract_art_return_type = string;
