// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface colpivot_params {
  out_table: unknown;

  in_query: unknown;

  key_cols: unknown[];

  class_cols: unknown[];

  value_e: unknown;

  col_order: unknown;
}
