// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface current_user_name_params {
}

/** Return type for current_user_name */
export type current_user_name_return_type = string;
