// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface dsql2_params {
  i_text: string;
}

/** Return type for dsql2 */
export type dsql2_return_type = number;
