// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.ek_kontrolljahre_ab */
enum EkKontrolljahreAb {
  ek = 'ek',
  ansiedlung = 'ansiedlung',
};

export default EkKontrolljahreAb;
