// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.ek_type */
enum EkType {
  ek = 'ek',
  ekf = 'ekf',
};

export default EkType;
