// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface is_valid_coordinates_params {
  $1: unknown;
}

/** Return type for is_valid_coordinates */
export type is_valid_coordinates_return_type = boolean;
