// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface lv95_x_params {
  $1: unknown;
}

export interface lv95_x_params {
  $1: unknown;
}

export interface lv95_x_params {
  $1: unknown;
}
