// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface uuid_or_null_params {
  str: string;
}

/** Return type for uuid_or_null */
export type uuid_or_null_return_type = string;
