// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface wgs84_lat_params {
  $1: unknown;
}

export interface wgs84_lat_params {
  $1: unknown;
}

export interface wgs84_lat_params {
  $1: unknown;
}
