/*
 * diese Views hängen von anderen ab, die in viewsGenerieren2.sql erstellt werden
 * daher muss dieser code NACH viewsGenerieren2.sql ausgeführt werden
 */

DROP VIEW IF EXISTS apflora.v_tpop_anzkontrinklletzterundletztertpopber CASCADE;
CREATE OR REPLACE VIEW apflora.v_tpop_anzkontrinklletzterundletztertpopber AS
SELECT
  apflora.v_tpop_anzkontrinklletzter.ap_id,
  apflora.v_tpop_anzkontrinklletzter.familie,
  apflora.v_tpop_anzkontrinklletzter.artname,
  apflora.v_tpop_anzkontrinklletzter.ap_bearb_stand,
  apflora.v_tpop_anzkontrinklletzter.ap_start_jahr,
  apflora.v_tpop_anzkontrinklletzter.ab_umsetzung_stand,
  apflora.v_tpop_anzkontrinklletzter.ap_verantwortlich,
  apflora.v_tpop_anzkontrinklletzter.pop_id,
  apflora.v_tpop_anzkontrinklletzter.pop_nr,
  apflora.v_tpop_anzkontrinklletzter.pop_name,
  apflora.v_tpop_anzkontrinklletzter.pop_status,
  apflora.v_tpop_anzkontrinklletzter.pop_bekannt_seit,
  apflora.v_tpop_anzkontrinklletzter.pop_status_unklar,
  apflora.v_tpop_anzkontrinklletzter.pop_status_unklar_begruendung,
  apflora.v_tpop_anzkontrinklletzter.pop_x,
  apflora.v_tpop_anzkontrinklletzter.pop_y,
  apflora.v_tpop_anzkontrinklletzter.id,
  apflora.v_tpop_anzkontrinklletzter.nr,
  apflora.v_tpop_anzkontrinklletzter.gemeinde,
  apflora.v_tpop_anzkontrinklletzter.flurname,
  apflora.v_tpop_anzkontrinklletzter.status,
  apflora.v_tpop_anzkontrinklletzter.bekannt_seit,
  apflora.v_tpop_anzkontrinklletzter.status_unklar,
  apflora.v_tpop_anzkontrinklletzter.status_unklar_grund,
  apflora.v_tpop_anzkontrinklletzter.x,
  apflora.v_tpop_anzkontrinklletzter.y,
  apflora.v_tpop_anzkontrinklletzter.radius,
  apflora.v_tpop_anzkontrinklletzter.hoehe,
  apflora.v_tpop_anzkontrinklletzter.exposition,
  apflora.v_tpop_anzkontrinklletzter.klima,
  apflora.v_tpop_anzkontrinklletzter.neigung,
  apflora.v_tpop_anzkontrinklletzter.beschreibung,
  apflora.v_tpop_anzkontrinklletzter.kataster_nr,
  apflora.v_tpop_anzkontrinklletzter.apber_relevant,
  apflora.v_tpop_anzkontrinklletzter.eigentuemer,
  apflora.v_tpop_anzkontrinklletzter.kontakt,
  apflora.v_tpop_anzkontrinklletzter.nutzungszone,
  apflora.v_tpop_anzkontrinklletzter.bewirtschafter,
  apflora.v_tpop_anzkontrinklletzter.bewirtschaftung,
  apflora.v_tpop_anzkontrinklletzter.changed,
  apflora.v_tpop_anzkontrinklletzter.changed_by,
  apflora.v_tpop_anzkontrinklletzter.anzahl_kontrollen,
  apflora.v_tpop_anzkontrinklletzter.kontr_id,
  apflora.v_tpop_anzkontrinklletzter.kontr_jahr,
  apflora.v_tpop_anzkontrinklletzter.kontr_datum,
  apflora.v_tpop_anzkontrinklletzter.kontr_typ,
  apflora.v_tpop_anzkontrinklletzter.kontr_bearbeiter,
  apflora.v_tpop_anzkontrinklletzter.kontr_ueberlebensrate,
  apflora.v_tpop_anzkontrinklletzter.kontr_vitalitaet,
  apflora.v_tpop_anzkontrinklletzter.kontr_entwicklung,
  apflora.v_tpop_anzkontrinklletzter.kontr_ursachen,
  apflora.v_tpop_anzkontrinklletzter.kontr_erfolgsbeurteilung,
  apflora.v_tpop_anzkontrinklletzter.kontr_umsetzung_aendern,
  apflora.v_tpop_anzkontrinklletzter.kontr_kontrolle_aendern,
  apflora.v_tpop_anzkontrinklletzter.kontr_bemerkungen,
  apflora.v_tpop_anzkontrinklletzter.kontr_lr_delarze,
  apflora.v_tpop_anzkontrinklletzter.kontr_lr_umgebung_delarze,
  apflora.v_tpop_anzkontrinklletzter.kontr_vegetationstyp,
  apflora.v_tpop_anzkontrinklletzter.kontr_konkurrenz,
  apflora.v_tpop_anzkontrinklletzter.kontr_moosschicht,
  apflora.v_tpop_anzkontrinklletzter.kontr_krautschicht,
  apflora.v_tpop_anzkontrinklletzter.kontr_strauchschicht,
  apflora.v_tpop_anzkontrinklletzter.kontr_baumschicht,
  apflora.v_tpop_anzkontrinklletzter.kontr_boden_typ,
  apflora.v_tpop_anzkontrinklletzter.kontr_boden_kalkgehalt,
  apflora.v_tpop_anzkontrinklletzter.kontr_boden_durchlaessigkeit,
  apflora.v_tpop_anzkontrinklletzter.kontr_boden_humus,
  apflora.v_tpop_anzkontrinklletzter.kontr_boden_naehrstoffgehalt,
  apflora.v_tpop_anzkontrinklletzter.kontr_boden_abtrag,
  apflora.v_tpop_anzkontrinklletzter.kontr_wasserhaushalt,
  apflora.v_tpop_anzkontrinklletzter.kontr_idealbiotop_uebereinstimmung,
  apflora.v_tpop_anzkontrinklletzter.kontr_handlungsbedarf,
  apflora.v_tpop_anzkontrinklletzter.kontr_flaeche_ueberprueft,
  apflora.v_tpop_anzkontrinklletzter.kontr_flaeche,
  apflora.v_tpop_anzkontrinklletzter.kontr_plan_vorhanden,
  apflora.v_tpop_anzkontrinklletzter.kontr_deckung_vegetation,
  apflora.v_tpop_anzkontrinklletzter.kontr_deckung_nackter_boden,
  apflora.v_tpop_anzkontrinklletzter.kontr_deckung_ap_art,
  apflora.v_tpop_anzkontrinklletzter.kontr_jungpflanzen_vorhanden,
  apflora.v_tpop_anzkontrinklletzter.kontr_vegetationshoehe_maximum,
  apflora.v_tpop_anzkontrinklletzter.kontr_vegetationshoehe_mittel,
  apflora.v_tpop_anzkontrinklletzter.kontr_gefaehrdung,
  apflora.v_tpop_anzkontrinklletzter.kontr_changed,
  apflora.v_tpop_anzkontrinklletzter.kontr_changed_by,
  apflora.v_tpop_anzkontrinklletzter.zaehlung_anzahlen,
  apflora.v_tpop_anzkontrinklletzter.zaehlung_einheiten,
  apflora.v_tpop_anzkontrinklletzter.zaehlung_methoden,
	apflora.v_tpopber_mitletzterid.tpopber_anz,
	apflora.v_tpopber_mitletzterid.id AS tpopber_id,
	apflora.v_tpopber_mitletzterid.jahr as tpopber_jahr,
	apflora.v_tpopber_mitletzterid.entwicklung as tpopber_entwicklung,
	apflora.v_tpopber_mitletzterid.bemerkungen as tpopber_bemerkungen,
	apflora.v_tpopber_mitletzterid.changed as tpopber_changed,
	apflora.v_tpopber_mitletzterid.changed_by  as tpopber_changed_by
FROM
	apflora.v_tpop_anzkontrinklletzter
  LEFT JOIN
    apflora.v_tpopber_mitletzterid
    ON apflora.v_tpop_anzkontrinklletzter.id = apflora.v_tpopber_mitletzterid.tpop_id;
