/* eslint-disable no-undef */

describe('Navigation', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('home directly opens Projekt', () => {
    cy.url().should('include', '/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13')
  })
  it('opens Aktionsplan Abies alba', () => {
    cy.get(
      '[data-url=\'["Projekte","e57f56f4-4376-11e8-ab21-4314b6749d13","Aktionspläne"]\']',
    )
      .click({ force: true })
      .wait(5000)
      .get(
        '[data-url=\'["Projekte","e57f56f4-4376-11e8-ab21-4314b6749d13","Aktionspläne","6c52d174-4f62-11e7-aebe-67a303eb0640"]\']',
      )
      .click({ force: true })
      .get('[data-id=form-title]')
      .should('contain', 'Aktionsplan')
  })
  it('toggles Tree 1', () => {
    cy.get('[data-id=tree-container1]')
      .should('exist')
      .get('[data-id=nav-tree1]')
      .click()
      .get('[data-id=tree-container1]')
      .should('not.exist')
      .get('[data-id=nav-tree1]')
      .click()
  })
  it('toggles Daten 1', () => {
    cy.get('[data-id=daten-container1]')
      .should('exist')
      .get('[data-id=nav-daten1]')
      .click()
      .wait(1000)
      .get('[data-id=daten-container1]')
      .should('not.exist')
      .get('[data-id=nav-daten1]')
      .click()
  })
  it('toggles Karte 1', () => {
    cy.get('[data-id=nav-karte1]')
      .click({ force: true })
      .wait(5000)
      .get('[data-id=karten-container1]')
      .should('exist')
      .get('[data-id=nav-karte1]')
      .click({ force: true })
      .get('[data-id=karten-container1]')
      .should('not.exist')
  })
  it('toggles Exporte', () => {
    cy.get('[data-id=nav-exporte]')
      .click({ force: true })
      .get('[data-id=exporte-container]')
      .should('exist')
      .get('[data-id=nav-exporte]')
      .click({ force: true })
      .get('[data-id=exporte-container]')
      .should('not.exist')
  })
  it('toggles Tree 2', () => {
    cy.get('[data-id=nav-tree2]')
      .click({ force: true })
      .wait(15000)
      .get('[data-id=tree-container2]')
      .should('exist')
      .get('[data-id=nav-tree2]')
      .click({ force: true })
      .get('[data-id=tree-container2]')
      .should('not.exist')
  })
  it('toggles Tree 2 and Daten 2', () => {
    cy.get('[data-id=nav-tree2]')
      .click({ force: true })
      .wait(15000)
      .get('[data-id=tree-container2]')
      .should('exist')
      .get('[data-id=nav-daten2]')
      .click({ force: true })
      .wait(5000)
      .get('[data-id=daten-container2]')
      .should('exist')
      .get('[data-id=nav-daten2]')
      .click({ force: true })
      .get('[data-id=daten-container2]')
      .should('not.exist')
      .get('[data-id=nav-tree2]')
      .click({ force: true })
      .get('[data-id=tree-container2]')
      .should('not.exist')
  })
})
