import { gql } from '@apollo/client'

export default gql`
  query tpopErsteUndLetzteKontrolleUndLetzterTpopbersQuery {
    allTpops(
      filter: { vTpopErsteUndLetzteKontrolleUndLetzterTpopbersByIdExist: true }
    ) {
      totalCount
      nodes {
        id
        # view: v_tpop_erste_und_letzte_kontrolle_und_letzter_tpopber
        vTpopErsteUndLetzteKontrolleUndLetzterTpopbersById {
          nodes {
            apId
            familie
            artname
            apBearbeitung
            apStartJahr
            apUmsetzung
            popId
            popNr
            popName
            popStatus
            popBekanntSeit
            popStatusUnklar
            popStatusUnklarBegruendung
            popX
            popY
            id
            nr
            gemeinde
            flurname
            status
            statusDecodiert
            bekanntSeit
            statusUnklar
            statusUnklarGrund
            x
            y
            radius
            hoehe
            exposition
            klima
            neigung
            beschreibung
            katasterNr
            apberRelevant
            apberRelevantGrund
            eigentuemer
            kontakt
            nutzungszone
            bewirtschafter
            bewirtschaftung
            bodenTyp
            bodenKalkgehalt
            bodenDurchlaessigkeit
            bodenHumus
            bodenNaehrstoffgehalt
            bodenAbtrag
            wasserhaushalt
            ekfrequenz
            ekfrequenzAbweichend
            createdAt
            updatedAt
            changedBy
            anzahlKontrollen
            ersteKontrolleId
            ersteKontrolleJahr
            ersteKontrolleDatum
            ersteKontrolleTyp
            ersteKontrolleBearbeiter
            ersteKontrolleUeberlebensrate
            ersteKontrolleVitalitaet
            ersteKontrolleEntwicklung
            ersteKontrolleUrsachen
            ersteKontrolleErfolgsbeurteilung
            ersteKontrolleUmsetzungAendern
            ersteKontrolleKontrolleAendern
            ersteKontrolleBemerkungen
            ersteKontrolleLrDelarze
            ersteKontrolleLrUmgebungDelarze
            ersteKontrolleVegetationstyp
            ersteKontrolleKonkurrenz
            ersteKontrolleMoosschicht
            ersteKontrolleKrautschicht
            ersteKontrolleStrauchschicht
            ersteKontrolleBaumschicht
            ersteKontrolleIdealbiotopUebereinstimmung
            ersteKontrolleHandlungsbedarf
            ersteKontrolleFlaecheUeberprueft
            ersteKontrolleFlaeche
            ersteKontrollePlanVorhanden
            ersteKontrolleDeckungVegetation
            ersteKontrolleDeckungNackterBoden
            ersteKontrolleDeckungApArt
            ersteKontrolleJungpflanzenVorhanden
            ersteKontrolleVegetationshoeheMaximum
            ersteKontrolleVegetationshoeheMittel
            ersteKontrolleGefaehrdung
            ersteKontrolleCreatedAt
            ersteKontrolleUpdatedAt
            ersteKontrolleChangedBy
            ersteKontrolleApberNichtRelevant
            ersteKontrolleApberNichtRelevantGrund
            ersteKontrolleEkfBemerkungen
            ersteKontrolleZaehlungAnzahlen
            ersteKontrolleZaehlungEinheiten
            ersteKontrolleZaehlungMethoden
            letzteKontrolleId
            letzteKontrolleJahr
            letzteKontrolleDatum
            letzteKontrolleTyp
            letzteKontrolleBearbeiter
            letzteKontrolleUeberlebensrate
            letzteKontrolleVitalitaet
            letzteKontrolleEntwicklung
            letzteKontrolleUrsachen
            letzteKontrolleErfolgsbeurteilung
            letzteKontrolleUmsetzungAendern
            letzteKontrolleKontrolleAendern
            letzteKontrolleBemerkungen
            letzteKontrolleLrDelarze
            letzteKontrolleLrUmgebungDelarze
            letzteKontrolleVegetationstyp
            letzteKontrolleKonkurrenz
            letzteKontrolleMoosschicht
            letzteKontrolleKrautschicht
            letzteKontrolleStrauchschicht
            letzteKontrolleBaumschicht
            letzteKontrolleIdealbiotopUebereinstimmung
            letzteKontrolleHandlungsbedarf
            letzteKontrolleFlaecheUeberprueft
            letzteKontrolleFlaeche
            letzteKontrollePlanVorhanden
            letzteKontrolleDeckungVegetation
            letzteKontrolleDeckungNackterBoden
            letzteKontrolleDeckungApArt
            letzteKontrolleJungpflanzenVorhanden
            letzteKontrolleVegetationshoeheMaximum
            letzteKontrolleVegetationshoeheMittel
            letzteKontrolleGefaehrdung
            letzteKontrolleCreatedAt
            letzteKontrolleUpdatedAt
            letzteKontrolleChangedBy
            letzteKontrolleApberNichtRelevant
            letzteKontrolleApberNichtRelevantGrund
            letzteKontrolleEkfBemerkungen
            letzteKontrolleZaehlungAnzahlen
            letzteKontrolleZaehlungEinheiten
            letzteKontrolleZaehlungMethoden
            tpopberAnz
            tpopberId
            tpopberJahr
            tpopberEntwicklung
            tpopberBemerkungen
            tpopberCreatedAt
            tpopberUpdatedAt
            tpopberChangedBy
          }
        }
      }
    }
  }
`
