// @flow

export const type = {
  nr: 'number',
  gemeinde: 'string',
  flurname: 'string',
  x: 'number',
  y: 'number',
  radius: 'number',
  hoehe: 'number',
  exposition: 'string',
  klima: 'string',
  neigung: 'string',
  beschreibung: 'string',
  katasterNr: 'string',
  status: 'number',
  statusUnklar: 'boolean',
  statusUnklarGrund: 'string',
  apberRelevant: 'number',
  bekanntSeit: 'number',
  eigentuemer: 'string',
  kontakt: 'string',
  nutzungszone: 'string',
  bewirtschafter: 'string',
  bewirtschaftung: 'string',
  kontrollfrequenz: 'number',
  kontrollfrequenzFreiwillige: 'number',
  bemerkungen: 'string',
}

export const initial = {
  nr: null,
  gemeinde: null,
  flurname: null,
  x: null,
  y: null,
  radius: null,
  hoehe: null,
  exposition: null,
  klima: null,
  neigung: null,
  beschreibung: null,
  katasterNr: null,
  status: null,
  statusUnklar: null,
  statusUnklarGrund: null,
  apberRelevant: null,
  bekanntSeit: null,
  eigentuemer: null,
  kontakt: null,
  nutzungszone: null,
  bewirtschafter: null,
  bewirtschaftung: null,
  kontrollfrequenz: null,
  kontrollfrequenzFreiwillige: null,
  bemerkungen: null,
}
