// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the foreignTable apflora.ae_lr_delarze */
export default interface AeLrDelarze {
  id: string;

  name: string;

  label: string;

  einheit: string;
}
