// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the foreignTable apflora.ae_taxonomies_download */
export default interface AeTaxonomiesDownload {
  taxonomie_id: string;

  taxonomie_name: string;

  id: string;

  taxid: number;

  taxid_intern: number;

  familie: string;

  artname: string;

  artwert: number;
}
