// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.ae_taxonomies */
export type AeTaxonomiesId = string & { __brand: 'apflora.ae_taxonomies' };

/** Represents the table apflora.ae_taxonomies */
export default interface AeTaxonomies {
  id: AeTaxonomiesId;

  taxonomie_id: string | null;

  taxonomie_name: string | null;

  taxid: number | null;

  familie: string | null;

  artname: string | null;

  artwert: number | null;

  tax_art_name: string | null;

  taxid_intern: number | null;
}

/** Represents the initializer for the table apflora.ae_taxonomies */
export interface AeTaxonomiesInitializer {
  id: AeTaxonomiesId;

  taxonomie_id?: string | null;

  taxonomie_name?: string | null;

  taxid?: number | null;

  familie?: string | null;

  artname?: string | null;

  artwert?: number | null;

  tax_art_name?: string | null;

  taxid_intern?: number | null;
}

/** Represents the mutator for the table apflora.ae_taxonomies */
export interface AeTaxonomiesMutator {
  id?: AeTaxonomiesId;

  taxonomie_id?: string | null;

  taxonomie_name?: string | null;

  taxid?: number | null;

  familie?: string | null;

  artname?: string | null;

  artwert?: number | null;

  tax_art_name?: string | null;

  taxid_intern?: number | null;
}
