// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.ap_bearbstand_werte */
export type ApBearbstandWerteId = string & { __brand: 'apflora.ap_bearbstand_werte' };

/** Represents the table apflora.ap_bearbstand_werte */
export default interface ApBearbstandWerte {
  /** Primärschlüssel */
  id: ApBearbstandWerteId;

  code: number | null;

  text: string | null;

  sort: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic: boolean | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.ap_bearbstand_werte */
export interface ApBearbstandWerteInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: ApBearbstandWerteId;

  /** Default value: nextval('apflora.ap_bearbstand_werte_code_seq'::regclass) */
  code?: number | null;

  /** Default value: NULL::character varying */
  text?: string | null;

  sort?: number | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /**
   * Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten
   * Default value: false
   */
  historic?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.ap_bearbstand_werte */
export interface ApBearbstandWerteMutator {
  /** Primärschlüssel */
  id?: ApBearbstandWerteId;

  code?: number | null;

  text?: string | null;

  sort?: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic?: boolean | null;

  created_at?: Date;

  updated_at?: Date;
}
