// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { AdresseId } from './Adresse';

/** Identifier type for apflora.apber */
export type ApberId = string & { __brand: 'apflora.apber' };

/**
 * Represents the table apflora.apber
 * (ap_id,jahr) references ap_history (id,year)
 */
export default interface Apber {
  /** Primärschlüssel */
  id: ApberId;

  /** Für welches Jahr gilt der Bericht? */
  jahr: number | null;

  /** Beschreibung der Situation im Berichtjahr. Seit 2017 nicht mehr verwendet: Früher wurden hier die Massnahmen aufgelistet */
  situation: string | null;

  /** Vergleich zu Vorjahr und Ausblick auf das Gesamtziel */
  vergleich_vorjahr_gesamtziel: string | null;

  /** Beurteilung des Erfolgs des Aktionsplans bisher */
  beurteilung: number | null;

  /** Veränderung gegenüber dem Vorjahr: plus heisst aufgestiegen, minus heisst abgestiegen */
  veraenderung_zum_vorjahr: string | null;

  /** Was sind die Ursachen fuer die beobachtete Entwicklung? */
  apber_analyse: string | null;

  /** Konsequenzen für die Umsetzung */
  konsequenzen_umsetzung: string | null;

  /** Konsequenzen für die Erfolgskontrolle */
  konsequenzen_erfolgskontrolle: string | null;

  /** Bemerkungen zum Aussagebereich A: Grundmengen und getroffene Massnahmen */
  biotope_neue: string | null;

  /** Bemerkungen zum Aussagebereich B: Bestandeskontrolle */
  biotope_optimieren: string | null;

  /** Bemerkungen zum Aussagebereich C: Zwischenbilanz zur Wirkung von Massnahmen */
  massnahmen_optimieren: string | null;

  /** Bemerkungen zum Aussagebereich D: Einschätzung der Wirkung des AP insgesamt pro Art */
  wirkung_auf_art: string | null;

  /** Datum der Nachführung */
  datum: Date | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Bemerkungen zum Aussagebereich C: Weitere Aktivitäten der Aktionsplan-Verantwortlichen */
  massnahmen_ap_bearb: string | null;

  /** Bemerkungen zum Aussagebereich C: Vergleich Ausführung/Planung */
  massnahmen_planung_vs_ausfuehrung: string | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id: ApId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter: AdresseId | null;

  created_at: Date;

  updated_at: Date;
}

/**
 * Represents the initializer for the table apflora.apber
 * (ap_id,jahr) references ap_history (id,year)
 */
export interface ApberInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: ApberId;

  /** Für welches Jahr gilt der Bericht? */
  jahr?: number | null;

  /** Beschreibung der Situation im Berichtjahr. Seit 2017 nicht mehr verwendet: Früher wurden hier die Massnahmen aufgelistet */
  situation?: string | null;

  /** Vergleich zu Vorjahr und Ausblick auf das Gesamtziel */
  vergleich_vorjahr_gesamtziel?: string | null;

  /** Beurteilung des Erfolgs des Aktionsplans bisher */
  beurteilung?: number | null;

  /**
   * Veränderung gegenüber dem Vorjahr: plus heisst aufgestiegen, minus heisst abgestiegen
   * Default value: NULL::character varying
   */
  veraenderung_zum_vorjahr?: string | null;

  /** Was sind die Ursachen fuer die beobachtete Entwicklung? */
  apber_analyse?: string | null;

  /** Konsequenzen für die Umsetzung */
  konsequenzen_umsetzung?: string | null;

  /** Konsequenzen für die Erfolgskontrolle */
  konsequenzen_erfolgskontrolle?: string | null;

  /** Bemerkungen zum Aussagebereich A: Grundmengen und getroffene Massnahmen */
  biotope_neue?: string | null;

  /** Bemerkungen zum Aussagebereich B: Bestandeskontrolle */
  biotope_optimieren?: string | null;

  /** Bemerkungen zum Aussagebereich C: Zwischenbilanz zur Wirkung von Massnahmen */
  massnahmen_optimieren?: string | null;

  /** Bemerkungen zum Aussagebereich D: Einschätzung der Wirkung des AP insgesamt pro Art */
  wirkung_auf_art?: string | null;

  /** Datum der Nachführung */
  datum?: Date | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Bemerkungen zum Aussagebereich C: Weitere Aktivitäten der Aktionsplan-Verantwortlichen */
  massnahmen_ap_bearb?: string | null;

  /** Bemerkungen zum Aussagebereich C: Vergleich Ausführung/Planung */
  massnahmen_planung_vs_ausfuehrung?: string | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id?: ApId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter?: AdresseId | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/**
 * Represents the mutator for the table apflora.apber
 * (ap_id,jahr) references ap_history (id,year)
 */
export interface ApberMutator {
  /** Primärschlüssel */
  id?: ApberId;

  /** Für welches Jahr gilt der Bericht? */
  jahr?: number | null;

  /** Beschreibung der Situation im Berichtjahr. Seit 2017 nicht mehr verwendet: Früher wurden hier die Massnahmen aufgelistet */
  situation?: string | null;

  /** Vergleich zu Vorjahr und Ausblick auf das Gesamtziel */
  vergleich_vorjahr_gesamtziel?: string | null;

  /** Beurteilung des Erfolgs des Aktionsplans bisher */
  beurteilung?: number | null;

  /** Veränderung gegenüber dem Vorjahr: plus heisst aufgestiegen, minus heisst abgestiegen */
  veraenderung_zum_vorjahr?: string | null;

  /** Was sind die Ursachen fuer die beobachtete Entwicklung? */
  apber_analyse?: string | null;

  /** Konsequenzen für die Umsetzung */
  konsequenzen_umsetzung?: string | null;

  /** Konsequenzen für die Erfolgskontrolle */
  konsequenzen_erfolgskontrolle?: string | null;

  /** Bemerkungen zum Aussagebereich A: Grundmengen und getroffene Massnahmen */
  biotope_neue?: string | null;

  /** Bemerkungen zum Aussagebereich B: Bestandeskontrolle */
  biotope_optimieren?: string | null;

  /** Bemerkungen zum Aussagebereich C: Zwischenbilanz zur Wirkung von Massnahmen */
  massnahmen_optimieren?: string | null;

  /** Bemerkungen zum Aussagebereich D: Einschätzung der Wirkung des AP insgesamt pro Art */
  wirkung_auf_art?: string | null;

  /** Datum der Nachführung */
  datum?: Date | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Bemerkungen zum Aussagebereich C: Weitere Aktivitäten der Aktionsplan-Verantwortlichen */
  massnahmen_ap_bearb?: string | null;

  /** Bemerkungen zum Aussagebereich C: Vergleich Ausführung/Planung */
  massnahmen_planung_vs_ausfuehrung?: string | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id?: ApId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter?: AdresseId | null;

  created_at?: Date;

  updated_at?: Date;
}
