// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';

/** Identifier type for apflora.ap_file */
export type ApFileId = string & { __brand: 'apflora.ap_file' };

/** Represents the table apflora.ap_file */
export default interface ApFile {
  id: ApFileId;

  ap_id: ApId | null;

  file_id: string | null;

  file_mime_type: string | null;

  name: string | null;

  beschreibung: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.ap_file */
export interface ApFileInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: ApFileId;

  ap_id?: ApId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.ap_file */
export interface ApFileMutator {
  id?: ApFileId;

  ap_id?: ApId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
