// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { QkName } from './Qk';

/** Represents the table apflora.apqk */
export default interface Apqk {
  ap_id: ApId;

  qk_name: QkName;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.apqk */
export interface ApqkInitializer {
  ap_id: ApId;

  qk_name: QkName;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.apqk */
export interface ApqkMutator {
  ap_id?: ApId;

  qk_name?: QkName;

  created_at?: Date;

  updated_at?: Date;
}
