// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';

/** Identifier type for apflora.ap_user */
export type ApUserId = string & { __brand: 'apflora.ap_user' };

/** Represents the table apflora.ap_user */
export default interface ApUser {
  id: ApUserId;

  ap_id: ApId | null;

  user_name: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.ap_user */
export interface ApUserInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: ApUserId;

  ap_id?: ApId | null;

  user_name?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.ap_user */
export interface ApUserMutator {
  id?: ApUserId;

  ap_id?: ApId | null;

  user_name?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
