// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AeTaxonomiesId } from './AeTaxonomies';
import type { ApId } from './Ap';

/** Identifier type for apflora.assozart */
export type AssozartId = string & { __brand: 'apflora.assozart' };

/** Represents the table apflora.assozart */
export default interface Assozart {
  /** Primärschlüssel */
  id: AssozartId;

  /** Bemerkungen zur Assoziation */
  bemerkungen: string | null;

  /** Wer hat den Datensatz zuletzt geändert? */
  changed_by: string | null;

  ae_id: AeTaxonomiesId | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id: ApId | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.assozart */
export interface AssozartInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: AssozartId;

  /** Bemerkungen zur Assoziation */
  bemerkungen?: string | null;

  /**
   * Wer hat den Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  ae_id?: AeTaxonomiesId | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id?: ApId | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.assozart */
export interface AssozartMutator {
  /** Primärschlüssel */
  id?: AssozartId;

  /** Bemerkungen zur Assoziation */
  bemerkungen?: string | null;

  /** Wer hat den Datensatz zuletzt geändert? */
  changed_by?: string | null;

  ae_id?: AeTaxonomiesId | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id?: ApId | null;

  created_at?: Date;

  updated_at?: Date;
}
