// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.ausw_pop_menge */
export default interface AuswPopMenge {
  jahr: number | null;

  values: unknown | null;
}
