// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.ch_administrative_unit */
export type ChAdministrativeUnitId = number & { __brand: 'apflora.ch_administrative_unit' };

/** Represents the table apflora.ch_administrative_unit */
export default interface ChAdministrativeUnit {
  id: ChAdministrativeUnitId;

  geom: unknown | null;

  gml_id: string | null;

  nationalcode: string | null;

  localid: string | null;

  namespace: string | null;

  versionid: string | null;

  localisedcharacterstring: string | null;

  country: string | null;

  language: string | null;

  nativeness: string | null;

  sourceofname: string | null;

  pronunciation: string | null;

  text: string | null;

  script: string | null;

  residenceofauthority: string | null;

  beginlifespanversion: string | null;

  boundary: string | null;
}

/** Represents the initializer for the table apflora.ch_administrative_unit */
export interface ChAdministrativeUnitInitializer {
  /** Default value: nextval('apflora.ch_administrative_unit_id_seq'::regclass) */
  id?: ChAdministrativeUnitId;

  geom?: unknown | null;

  gml_id?: string | null;

  nationalcode?: string | null;

  localid?: string | null;

  namespace?: string | null;

  versionid?: string | null;

  localisedcharacterstring?: string | null;

  country?: string | null;

  language?: string | null;

  nativeness?: string | null;

  sourceofname?: string | null;

  pronunciation?: string | null;

  text?: string | null;

  script?: string | null;

  residenceofauthority?: string | null;

  beginlifespanversion?: string | null;

  boundary?: string | null;
}

/** Represents the mutator for the table apflora.ch_administrative_unit */
export interface ChAdministrativeUnitMutator {
  id?: ChAdministrativeUnitId;

  geom?: unknown | null;

  gml_id?: string | null;

  nationalcode?: string | null;

  localid?: string | null;

  namespace?: string | null;

  versionid?: string | null;

  localisedcharacterstring?: string | null;

  country?: string | null;

  language?: string | null;

  nativeness?: string | null;

  sourceofname?: string | null;

  pronunciation?: string | null;

  text?: string | null;

  script?: string | null;

  residenceofauthority?: string | null;

  beginlifespanversion?: string | null;

  boundary?: string | null;
}
