// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.currentissue */
export type CurrentissueId = string & { __brand: 'apflora.currentissue' };

/** Represents the table apflora.currentissue */
export default interface Currentissue {
  id: CurrentissueId;

  sort: number | null;

  title: string | null;

  /** Bekannter Fehler */
  issue: string | null;
}

/** Represents the initializer for the table apflora.currentissue */
export interface CurrentissueInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: CurrentissueId;

  sort?: number | null;

  title?: string | null;

  /** Bekannter Fehler */
  issue?: string | null;
}

/** Represents the mutator for the table apflora.currentissue */
export interface CurrentissueMutator {
  id?: CurrentissueId;

  sort?: number | null;

  title?: string | null;

  /** Bekannter Fehler */
  issue?: string | null;
}
