// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.detailplaene */
export type DetailplaeneId = string & { __brand: 'apflora.detailplaene' };

/** Represents the table apflora.detailplaene */
export default interface Detailplaene {
  id: DetailplaeneId;

  data: unknown | null;

  geom: unknown | null;

  created_at: Date;

  updated_at: Date;

  changed_by: string | null;
}

/** Represents the initializer for the table apflora.detailplaene */
export interface DetailplaeneInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: DetailplaeneId;

  data?: unknown | null;

  /** Default value: NULL::geometry */
  geom?: unknown | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;

  /** Default value: NULL::character varying */
  changed_by?: string | null;
}

/** Represents the mutator for the table apflora.detailplaene */
export interface DetailplaeneMutator {
  id?: DetailplaeneId;

  data?: unknown | null;

  geom?: unknown | null;

  created_at?: Date;

  updated_at?: Date;

  changed_by?: string | null;
}
