// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.detailplaene_in */
export type DetailplaeneInOgcFid = number & { __brand: 'apflora.detailplaene_in' };

/** Represents the table apflora.detailplaene_in */
export default interface DetailplaeneIn {
  ogc_fid: DetailplaeneInOgcFid;

  wkb_geometry: unknown | null;

  shape_leng: string | null;

  shape_area: string | null;

  nr: string | null;

  typ: string | null;
}

/** Represents the initializer for the table apflora.detailplaene_in */
export interface DetailplaeneInInitializer {
  /** Default value: nextval('apflora.detailplaene_in_ogc_fid_seq'::regclass) */
  ogc_fid?: DetailplaeneInOgcFid;

  wkb_geometry?: unknown | null;

  shape_leng?: string | null;

  shape_area?: string | null;

  nr?: string | null;

  typ?: string | null;
}

/** Represents the mutator for the table apflora.detailplaene_in */
export interface DetailplaeneInMutator {
  ogc_fid?: DetailplaeneInOgcFid;

  wkb_geometry?: unknown | null;

  shape_leng?: string | null;

  shape_area?: string | null;

  nr?: string | null;

  typ?: string | null;
}
