// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.ek_abrechnungstyp_werte */
export type EkAbrechnungstypWerteId = string & { __brand: 'apflora.ek_abrechnungstyp_werte' };

/** Represents the table apflora.ek_abrechnungstyp_werte */
export default interface EkAbrechnungstypWerte {
  /** Primärschlüssel */
  id: EkAbrechnungstypWerteId;

  code: string | null;

  text: string | null;

  sort: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic: boolean | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.ek_abrechnungstyp_werte */
export interface EkAbrechnungstypWerteInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: EkAbrechnungstypWerteId;

  code?: string | null;

  /** Default value: NULL::character varying */
  text?: string | null;

  sort?: number | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /**
   * Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten
   * Default value: false
   */
  historic?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.ek_abrechnungstyp_werte */
export interface EkAbrechnungstypWerteMutator {
  /** Primärschlüssel */
  id?: EkAbrechnungstypWerteId;

  code?: string | null;

  text?: string | null;

  sort?: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic?: boolean | null;

  created_at?: Date;

  updated_at?: Date;
}
