// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';

/** Identifier type for apflora.erfkrit */
export type ErfkritId = string & { __brand: 'apflora.erfkrit' };

/**
 * Represents the table apflora.erfkrit
 * (ap_id) references ap_history (id)
 */
export default interface Erfkrit {
  /** Primärschlüssel */
  id: ErfkritId;

  /** Wie gut werden die Ziele erreicht? Auswahl aus der Tabelle "ap_erfkrit_werte" */
  erfolg: number | null;

  /** Beschreibung der Kriterien für den Erfolg */
  kriterien: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id: ApId | null;

  created_at: Date;

  updated_at: Date;
}

/**
 * Represents the initializer for the table apflora.erfkrit
 * (ap_id) references ap_history (id)
 */
export interface ErfkritInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: ErfkritId;

  /** Wie gut werden die Ziele erreicht? Auswahl aus der Tabelle "ap_erfkrit_werte" */
  erfolg?: number | null;

  /** Beschreibung der Kriterien für den Erfolg */
  kriterien?: string | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id?: ApId | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/**
 * Represents the mutator for the table apflora.erfkrit
 * (ap_id) references ap_history (id)
 */
export interface ErfkritMutator {
  /** Primärschlüssel */
  id?: ErfkritId;

  /** Wie gut werden die Ziele erreicht? Auswahl aus der Tabelle "ap_erfkrit_werte" */
  erfolg?: number | null;

  /** Beschreibung der Kriterien für den Erfolg */
  kriterien?: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Zugehöriger Aktionsplan. Fremdschlüssel aus der Tabelle "ap" */
  ap_id?: ApId | null;

  created_at?: Date;

  updated_at?: Date;
}
