// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.forstrevier */
export type ForstrevierOgcFid = number & { __brand: 'apflora.forstrevier' };

/** Represents the table apflora.forstrevier */
export default interface Forstrevier {
  ogc_fid: ForstrevierOgcFid;

  wkb_geometry: unknown | null;

  forevnr: string | null;

  flaeche_ha: string | null;

  rev_name: string | null;

  shape_area: string | null;

  shape_len: string | null;
}

/** Represents the initializer for the table apflora.forstrevier */
export interface ForstrevierInitializer {
  /** Default value: nextval('apflora.forstreviere_ogc_fid_seq'::regclass) */
  ogc_fid?: ForstrevierOgcFid;

  wkb_geometry?: unknown | null;

  forevnr?: string | null;

  flaeche_ha?: string | null;

  rev_name?: string | null;

  shape_area?: string | null;

  shape_len?: string | null;
}

/** Represents the mutator for the table apflora.forstrevier */
export interface ForstrevierMutator {
  ogc_fid?: ForstrevierOgcFid;

  wkb_geometry?: unknown | null;

  forevnr?: string | null;

  flaeche_ha?: string | null;

  rev_name?: string | null;

  shape_area?: string | null;

  shape_len?: string | null;
}
