// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface historize_for_ap_params {
  _year: number;

  ap_id: string;
}

/** Return type for historize_for_ap */
export type historize_for_ap_return_type = boolean;
