// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface historize_params {
  _year: number;
}

/** Return type for historize */
export type historize_return_type = boolean;
