// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { IdealbiotopId } from './Idealbiotop';

/** Identifier type for apflora.idealbiotop_file */
export type IdealbiotopFileId = string & { __brand: 'apflora.idealbiotop_file' };

/** Represents the table apflora.idealbiotop_file */
export default interface IdealbiotopFile {
  id: IdealbiotopFileId;

  idealbiotop_id: IdealbiotopId | null;

  file_id: string | null;

  file_mime_type: string | null;

  name: string | null;

  beschreibung: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.idealbiotop_file */
export interface IdealbiotopFileInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: IdealbiotopFileId;

  idealbiotop_id?: IdealbiotopId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.idealbiotop_file */
export interface IdealbiotopFileMutator {
  id?: IdealbiotopFileId;

  idealbiotop_id?: IdealbiotopId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
