// barrel for the types that components import most often;
// not generated by Kanel — extend manually as needed
export type { AdresseId } from './Adresse.ts'
export type { AeTaxonomiesId } from './AeTaxonomies.ts'
export type { ApId } from './Ap.ts'
export type { ApberId } from './Apber.ts'
export type { AssozartId } from './Assozart.ts'
export type { BeobId } from './Beob.ts'
export type { default as Ekfrequenz } from './Ekfrequenz.ts'
export type { EkfrequenzId } from './Ekfrequenz.ts'
export type { default as Ekzaehleinheit } from './Ekzaehleinheit.ts'
export type { EkzaehleinheitId } from './Ekzaehleinheit.ts'
export type { default as Erfkrit } from './Erfkrit.ts'
export type { ErfkritId } from './Erfkrit.ts'
export type { default as Idealbiotop } from './Idealbiotop.ts'
export type { IdealbiotopId } from './Idealbiotop.ts'
export type { default as Message } from './Message.ts'
export type { default as Pop } from './Pop.ts'
export type { PopId } from './Pop.ts'
export type { PopberId } from './Popber.ts'
export type { PopmassnberId } from './Popmassnber.ts'
export type { ProjektId } from './Projekt.ts'
export type { QkName } from './Qk.ts'
export type { TpopId } from './Tpop.ts'
export type { TpopkontrId } from './Tpopkontr.ts'
export type { TpopkontrzaehlEinheitWerteId } from './TpopkontrzaehlEinheitWerte.ts'
export type { TpopkontrzaehlId } from './Tpopkontrzaehl.ts'
export type { TpopmassnId } from './Tpopmassn.ts'
export type { UserId } from './User.ts'
export type { ZielId } from './Ziel.ts'

// the following never existed in the (generated) models;
// they model the wert-table code columns, which are plain strings
export type ApErfkritWerteCode = string
export type ApqkQkName = string
export type EkAbrechnungstypWerteCode = string
export type PopStatusWerteCode = string
export type TpopApberrelevantGrundWerteCode = string
export type TpopEntwicklungWerteCode = string
export type TpopStatusWerteCode = string
export type TpopmassnErfbeurtWerteCode = string
export type ZielTypWerteCode = string
