// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AeTaxonomiesId } from './AeTaxonomies';

/** Identifier type for apflora.infoflora20250407beob */
export type Infoflora20250407beobId = string & { __brand: 'apflora.infoflora20250407beob' };

/** Represents the table apflora.infoflora20250407beob */
export default interface Infoflora20250407beob {
  id: Infoflora20250407beobId;

  external_id: string | null;

  obs_id: number | null;

  is_apflora_ek: boolean | null;

  already_imported: boolean | null;

  quelle: string | null;

  id_field: string | null;

  art_id: AeTaxonomiesId | null;

  art_id_original: AeTaxonomiesId | null;

  datum: Date | null;

  autor: string | null;

  geom_point: unknown | null;

  data: unknown | null;

  changed: Date | null;

  changed_by: string | null;
}

/** Represents the initializer for the table apflora.infoflora20250407beob */
export interface Infoflora20250407beobInitializer {
  /** Default value: gen_random_uuid() */
  id?: Infoflora20250407beobId;

  external_id?: string | null;

  obs_id?: number | null;

  /** Default value: false */
  is_apflora_ek?: boolean | null;

  /** Default value: false */
  already_imported?: boolean | null;

  quelle?: string | null;

  /** Default value: NULL::character varying */
  id_field?: string | null;

  art_id?: AeTaxonomiesId | null;

  art_id_original?: AeTaxonomiesId | null;

  datum?: Date | null;

  /** Default value: NULL::character varying */
  autor?: string | null;

  /** Default value: NULL::geometry */
  geom_point?: unknown | null;

  data?: unknown | null;

  /** Default value: now() */
  changed?: Date | null;

  /** Default value: NULL::character varying */
  changed_by?: string | null;
}

/** Represents the mutator for the table apflora.infoflora20250407beob */
export interface Infoflora20250407beobMutator {
  id?: Infoflora20250407beobId;

  external_id?: string | null;

  obs_id?: number | null;

  is_apflora_ek?: boolean | null;

  already_imported?: boolean | null;

  quelle?: string | null;

  id_field?: string | null;

  art_id?: AeTaxonomiesId | null;

  art_id_original?: AeTaxonomiesId | null;

  datum?: Date | null;

  autor?: string | null;

  geom_point?: unknown | null;

  data?: unknown | null;

  changed?: Date | null;

  changed_by?: string | null;
}
