// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.infoflora20250407original */
export type Infoflora20250407originalObsId = number & { __brand: 'apflora.infoflora20250407original' };

/** Represents the table apflora.infoflora20250407original */
export default interface Infoflora20250407original {
  obs_id: Infoflora20250407originalObsId;

  sisf_id: number | null;

  tax_id_intern: number | null;

  taxon: string | null;

  obs_day: number | null;

  obs_month: number | null;

  obs_year: number | null;

  observers: string | null;

  country: string | null;

  canton: string | null;

  municipality: string | null;

  region_biogeo: string | null;

  spatial_resolution: string | null;

  x_swiss: string | null;

  y_swiss: string | null;

  xy_type: string | null;

  xy_radius: string | null;

  geo_expert: string | null;

  locality_descript: string | null;

  altitude_min: number | null;

  altitude_max: number | null;

  altitude_expert: string | null;

  abundance_cat: string | null;

  count_unit: string | null;

  abundance: string | null;

  remarks: string | null;

  typo_ch: number | null;

  phenology_code: number | null;

  citation: string | null;

  project_id: number | null;

  project_name: string | null;

  external_id: string | null;

  obs_type: string | null;

  specimen_type: string | null;

  herbarium_localization: string | null;

  herbarium_collection: string | null;

  external_uid: string | null;

  reference: string | null;

  native_status: string | null;

  redlist: string | null;

  regional_redlist: string | null;

  priority: string | null;

  measures: number | null;

  monitoring: number | null;

  ch_protection: number | null;

  cantonal_protection: number | null;

  uzl: string | null;

  wzl: string | null;

  invasive: string | null;

  taxon_link: string | null;

  family: string | null;

  name_de: string | null;
}

/** Represents the initializer for the table apflora.infoflora20250407original */
export interface Infoflora20250407originalInitializer {
  obs_id: Infoflora20250407originalObsId;

  sisf_id?: number | null;

  tax_id_intern?: number | null;

  taxon?: string | null;

  obs_day?: number | null;

  obs_month?: number | null;

  obs_year?: number | null;

  observers?: string | null;

  country?: string | null;

  canton?: string | null;

  municipality?: string | null;

  region_biogeo?: string | null;

  spatial_resolution?: string | null;

  x_swiss?: string | null;

  y_swiss?: string | null;

  xy_type?: string | null;

  xy_radius?: string | null;

  geo_expert?: string | null;

  locality_descript?: string | null;

  altitude_min?: number | null;

  altitude_max?: number | null;

  altitude_expert?: string | null;

  abundance_cat?: string | null;

  count_unit?: string | null;

  abundance?: string | null;

  remarks?: string | null;

  typo_ch?: number | null;

  phenology_code?: number | null;

  citation?: string | null;

  project_id?: number | null;

  project_name?: string | null;

  external_id?: string | null;

  obs_type?: string | null;

  specimen_type?: string | null;

  herbarium_localization?: string | null;

  herbarium_collection?: string | null;

  external_uid?: string | null;

  reference?: string | null;

  native_status?: string | null;

  redlist?: string | null;

  regional_redlist?: string | null;

  priority?: string | null;

  measures?: number | null;

  monitoring?: number | null;

  ch_protection?: number | null;

  cantonal_protection?: number | null;

  uzl?: string | null;

  wzl?: string | null;

  invasive?: string | null;

  taxon_link?: string | null;

  family?: string | null;

  name_de?: string | null;
}

/** Represents the mutator for the table apflora.infoflora20250407original */
export interface Infoflora20250407originalMutator {
  obs_id?: Infoflora20250407originalObsId;

  sisf_id?: number | null;

  tax_id_intern?: number | null;

  taxon?: string | null;

  obs_day?: number | null;

  obs_month?: number | null;

  obs_year?: number | null;

  observers?: string | null;

  country?: string | null;

  canton?: string | null;

  municipality?: string | null;

  region_biogeo?: string | null;

  spatial_resolution?: string | null;

  x_swiss?: string | null;

  y_swiss?: string | null;

  xy_type?: string | null;

  xy_radius?: string | null;

  geo_expert?: string | null;

  locality_descript?: string | null;

  altitude_min?: number | null;

  altitude_max?: number | null;

  altitude_expert?: string | null;

  abundance_cat?: string | null;

  count_unit?: string | null;

  abundance?: string | null;

  remarks?: string | null;

  typo_ch?: number | null;

  phenology_code?: number | null;

  citation?: string | null;

  project_id?: number | null;

  project_name?: string | null;

  external_id?: string | null;

  obs_type?: string | null;

  specimen_type?: string | null;

  herbarium_localization?: string | null;

  herbarium_collection?: string | null;

  external_uid?: string | null;

  reference?: string | null;

  native_status?: string | null;

  redlist?: string | null;

  regional_redlist?: string | null;

  priority?: string | null;

  measures?: number | null;

  monitoring?: number | null;

  ch_protection?: number | null;

  cantonal_protection?: number | null;

  uzl?: string | null;

  wzl?: string | null;

  invasive?: string | null;

  taxon_link?: string | null;

  family?: string | null;

  name_de?: string | null;
}
