// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.jber_abc */
export default interface JberAbc {
  artname: string | null;

  id: string | null;

  start_jahr: number | null;

  bearbeiter: string | null;

  bearbeitung: number | null;

  a_3_l_pop: number | null;

  a_3_l_tpop: number | null;

  a_4_l_pop: number | null;

  a_4_l_tpop: number | null;

  a_5_l_pop: number | null;

  a_5_l_tpop: number | null;

  a_7_l_pop: number | null;

  a_7_l_tpop: number | null;

  a_8_l_pop: number | null;

  a_8_l_tpop: number | null;

  a_9_l_pop: number | null;

  a_9_l_tpop: number | null;

  b_1_l_pop: number | null;

  b_1_l_tpop: number | null;

  b_1_first_year: number | null;

  b_1_r_pop: number | null;

  b_1_r_tpop: number | null;

  c_1_l_pop: number | null;

  c_1_l_tpop: number | null;

  c_1_r_pop: number | null;

  c_1_r_tpop: number | null;

  c_1_first_year: number | null;

  first_massn: number | null;

  c_2_r_pop: number | null;

  c_2_r_tpop: number | null;

  c_3_r_pop: number | null;

  c_3_r_tpop: number | null;

  c_4_r_pop: number | null;

  c_4_r_tpop: number | null;

  c_5_r_pop: number | null;

  c_5_r_tpop: number | null;

  c_6_r_pop: number | null;

  c_6_r_tpop: number | null;

  c_7_r_pop: number | null;

  c_7_r_tpop: number | null;

  erfolg: number | null;

  erfolg_vorjahr: number | null;
}
