// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.jber_akt_pop */
export default interface JberAktPop {
  artname: string | null;

  id: string | null;

  pop_100: number | null;

  pop_200: number | null;

  pop_total: number | null;

  pop_100_diff: number | null;

  pop_200_diff: number | null;

  pop_total_diff: number | null;
}
