// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.markierungen */
export type MarkierungenOgcFid = number & { __brand: 'apflora.markierungen' };

/**
 * Represents the table apflora.markierungen
 * Markierungen, die im Rahmen von apflora gesetzt wurden. Quelle: Topos
 */
export default interface Markierungen {
  ogc_fid: MarkierungenOgcFid;

  wkb_geometry: unknown | null;

  gebiet: string | null;

  pfostennum: string | null;

  markierung: string | null;
}

/**
 * Represents the initializer for the table apflora.markierungen
 * Markierungen, die im Rahmen von apflora gesetzt wurden. Quelle: Topos
 */
export interface MarkierungenInitializer {
  /** Default value: nextval('apflora.markierungen_ogc_fid_seq'::regclass) */
  ogc_fid?: MarkierungenOgcFid;

  wkb_geometry?: unknown | null;

  gebiet?: string | null;

  pfostennum?: string | null;

  markierung?: string | null;
}

/**
 * Represents the mutator for the table apflora.markierungen
 * Markierungen, die im Rahmen von apflora gesetzt wurden. Quelle: Topos
 */
export interface MarkierungenMutator {
  ogc_fid?: MarkierungenOgcFid;

  wkb_geometry?: unknown | null;

  gebiet?: string | null;

  pfostennum?: string | null;

  markierung?: string | null;
}
