// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.message */
export type MessageId = string & { __brand: 'apflora.message' };

/** Represents the table apflora.message */
export default interface Message {
  id: MessageId;

  /** Nachricht an die Benutzer */
  message: string;

  time: Date;

  active: boolean;
}

/** Represents the initializer for the table apflora.message */
export interface MessageInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: MessageId;

  /** Nachricht an die Benutzer */
  message: string;

  /** Default value: now() */
  time?: Date;

  /** Default value: true */
  active?: boolean;
}

/** Represents the mutator for the table apflora.message */
export interface MessageMutator {
  id?: MessageId;

  /** Nachricht an die Benutzer */
  message?: string;

  time?: Date;

  active?: boolean;
}
