// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.nearest_tpop_for_ap_resp */
export default interface NearestTpopForApResp {
  id: string | null;

  pop_id: string | null;
}
