// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.ns_betreuung */
export type NsBetreuungGebietNr = number & { __brand: 'apflora.ns_betreuung' };

/**
 * Represents the table apflora.ns_betreuung
 * Von der FNS. Um zu das wfs betreuungsgebiete mit den Betreuern zu verknüpfen
 */
export default interface NsBetreuung {
  gebiet_nr: NsBetreuungGebietNr;

  gebiet_name: string | null;

  firma: string | null;

  projektleiter: string | null;

  telefon: string | null;

  geom: unknown | null;
}

/**
 * Represents the initializer for the table apflora.ns_betreuung
 * Von der FNS. Um zu das wfs betreuungsgebiete mit den Betreuern zu verknüpfen
 */
export interface NsBetreuungInitializer {
  gebiet_nr: NsBetreuungGebietNr;

  gebiet_name?: string | null;

  firma?: string | null;

  projektleiter?: string | null;

  telefon?: string | null;

  /** Default value: NULL::geometry */
  geom?: unknown | null;
}

/**
 * Represents the mutator for the table apflora.ns_betreuung
 * Von der FNS. Um zu das wfs betreuungsgebiete mit den Betreuern zu verknüpfen
 */
export interface NsBetreuungMutator {
  gebiet_nr?: NsBetreuungGebietNr;

  gebiet_name?: string | null;

  firma?: string | null;

  projektleiter?: string | null;

  telefon?: string | null;

  geom?: unknown | null;
}
