// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface pop_ausw_tpop_menge_params {
  popid: string;
}

export interface pop_ausw_tpop_menge_params {
  popid: string;

  jahr: number;
}
