// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PopId } from './Pop';

/** Identifier type for apflora.pop_file */
export type PopFileId = string & { __brand: 'apflora.pop_file' };

/** Represents the table apflora.pop_file */
export default interface PopFile {
  id: PopFileId;

  pop_id: PopId | null;

  file_id: string | null;

  file_mime_type: string | null;

  name: string | null;

  beschreibung: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.pop_file */
export interface PopFileInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: PopFileId;

  pop_id?: PopId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.pop_file */
export interface PopFileMutator {
  id?: PopFileId;

  pop_id?: PopId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
