// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.pop_nach_status_for_jber */
export default interface PopNachStatusForJber {
  year: number | null;

  a3lpop: number | null;

  a4lpop: number | null;

  a5lpop: number | null;

  a7lpop: number | null;

  a8lpop: number | null;

  a9lpop: number | null;
}
