// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.pop_status_werte */
export type PopStatusWerteId = string & { __brand: 'apflora.pop_status_werte' };

/** Represents the table apflora.pop_status_werte */
export default interface PopStatusWerte {
  /** Primärschlüssel */
  id: PopStatusWerteId;

  code: number | null;

  /** Beschreibung der Herkunft */
  text: string | null;

  sort: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic: boolean | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.pop_status_werte */
export interface PopStatusWerteInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: PopStatusWerteId;

  /** Default value: nextval('apflora.pop_status_werte_code_seq'::regclass) */
  code?: number | null;

  /**
   * Beschreibung der Herkunft
   * Default value: NULL::character varying
   */
  text?: string | null;

  sort?: number | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /**
   * Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten
   * Default value: false
   */
  historic?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.pop_status_werte */
export interface PopStatusWerteMutator {
  /** Primärschlüssel */
  id?: PopStatusWerteId;

  code?: number | null;

  /** Beschreibung der Herkunft */
  text?: string | null;

  sort?: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic?: boolean | null;

  created_at?: Date;

  updated_at?: Date;
}
