// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.projekt */
export type ProjektId = string & { __brand: 'apflora.projekt' };

/** Represents the table apflora.projekt */
export default interface Projekt {
  id: ProjektId;

  name: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.projekt */
export interface ProjektInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: ProjektId;

  /** Default value: NULL::character varying */
  name?: string | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.projekt */
export interface ProjektMutator {
  id?: ProjektId;

  name?: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
