// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface q_tpop_counted_einheit_multiple_times_in_year_params {
  projid: string;

  apid: string;

  berichtjahr: number;
}
