// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface q_tpop_mit_aktuellen_kontrollen_ohne_zielrelevante_einheit_params {
  berichtjahr: number;

  proj_id: string;

  ap_id: string;
}
