// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.q_ap_mit_aktuellen_kontrollen_ohne_zielrelevante_einheit */
export default interface QApMitAktuellenKontrollenOhneZielrelevanteEinheit {
  proj_id: string | null;

  ap_id: string | null;
}
