// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.q_pop_ohne_popmassnber */
export default interface QPopOhnePopmassnber {
  proj_id: string | null;

  ap_id: string | null;

  id: string | null;

  nr: number | null;
}
