// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.q_tpop_counted_einheit_multiple_times_in_year */
export default interface QTpopCountedEinheitMultipleTimesInYear {
  proj_id: string | null;

  ap_id: string | null;

  pop_id: string | null;

  pop_nr: number | null;

  id: string | null;

  nr: number | null;

  einheit: string | null;

  anzahl: string | null;
}
