// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.q_tpop_mit_aktuellen_anpflanzungen_ohne_zielrelevante_einheit */
export default interface QTpopMitAktuellenAnpflanzungenOhneZielrelevanteEinheit {
  proj_id: string | null;

  ap_id: string | null;

  pop_id: string | null;

  pop_nr: number | null;

  id: string | null;

  nr: number | null;
}
