// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.q_tpop_ohne_massnber */
export default interface QTpopOhneMassnber {
  proj_id: string | null;

  ap_id: string | null;

  pop_id: string | null;

  pop_nr: number | null;

  id: string | null;

  nr: number | null;
}
