// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApHistoryYear } from './ApHistory';
import type { PopHistoryId } from './PopHistory';

/** Identifier type for apflora.tpop_history */
export type TpopHistoryId = string & { __brand: 'apflora.tpop_history' };

/**
 * Represents the table apflora.tpop_history
 * @foreignKey (pop_id) references pop (id)\n@foreignKey (status) references pop_status_werte (code)\n@foreignKey (apber_relevant_grund) references tpop_apberrelevant_grund_werte (code)\n@foreignKey (ekfrequenz) references ekfrequenz (id)\n@foreignKey (ekf_kontrolleur) references adresse (id)
 */
export default interface TpopHistory {
  /** Jahr: tpop_history wurde beim Erstellen des Jahresberichts im Februar des Folgejahrs von tpop kopiert */
  year: ApHistoryYear;

  /** Primärschlüssel der Tabelle tpop */
  id: TpopHistoryId;

  pop_id: PopHistoryId | null;

  nr: number | null;

  gemeinde: string | null;

  flurname: string | null;

  geom_point: unknown | null;

  radius: number | null;

  hoehe: number | null;

  exposition: string | null;

  klima: string | null;

  neigung: string | null;

  beschreibung: string | null;

  kataster_nr: string | null;

  status: number | null;

  status_unklar: boolean | null;

  status_unklar_grund: string | null;

  apber_relevant: boolean | null;

  apber_relevant_grund: number | null;

  bekannt_seit: number | null;

  eigentuemer: string | null;

  kontakt: string | null;

  nutzungszone: string | null;

  bewirtschafter: string | null;

  bewirtschaftung: string | null;

  ekfrequenz: string | null;

  ekfrequenz_startjahr: number | null;

  ekfrequenz_abweichend: boolean | null;

  ekf_kontrolleur: string | null;

  bemerkungen: string | null;

  changed_by: string | null;

  boden_typ: string | null;

  boden_kalkgehalt: string | null;

  boden_durchlaessigkeit: string | null;

  boden_humus: string | null;

  boden_naehrstoffgehalt: string | null;

  boden_abtrag: string | null;

  wasserhaushalt: string | null;

  created_at: Date;

  updated_at: Date;
}

/**
 * Represents the initializer for the table apflora.tpop_history
 * @foreignKey (pop_id) references pop (id)\n@foreignKey (status) references pop_status_werte (code)\n@foreignKey (apber_relevant_grund) references tpop_apberrelevant_grund_werte (code)\n@foreignKey (ekfrequenz) references ekfrequenz (id)\n@foreignKey (ekf_kontrolleur) references adresse (id)
 */
export interface TpopHistoryInitializer {
  /** Jahr: tpop_history wurde beim Erstellen des Jahresberichts im Februar des Folgejahrs von tpop kopiert */
  year: ApHistoryYear;

  /** Primärschlüssel der Tabelle tpop */
  id: TpopHistoryId;

  pop_id?: PopHistoryId | null;

  nr?: number | null;

  gemeinde?: string | null;

  flurname?: string | null;

  /** Default value: NULL::geometry */
  geom_point?: unknown | null;

  radius?: number | null;

  hoehe?: number | null;

  /** Default value: NULL::character varying */
  exposition?: string | null;

  /** Default value: NULL::character varying */
  klima?: string | null;

  /** Default value: NULL::character varying */
  neigung?: string | null;

  beschreibung?: string | null;

  kataster_nr?: string | null;

  status?: number | null;

  /** Default value: false */
  status_unklar?: boolean | null;

  status_unklar_grund?: string | null;

  /** Default value: true */
  apber_relevant?: boolean | null;

  apber_relevant_grund?: number | null;

  bekannt_seit?: number | null;

  eigentuemer?: string | null;

  kontakt?: string | null;

  nutzungszone?: string | null;

  bewirtschafter?: string | null;

  bewirtschaftung?: string | null;

  ekfrequenz?: string | null;

  ekfrequenz_startjahr?: number | null;

  /** Default value: false */
  ekfrequenz_abweichend?: boolean | null;

  ekf_kontrolleur?: string | null;

  bemerkungen?: string | null;

  /** Default value: NULL::character varying */
  changed_by?: string | null;

  boden_typ?: string | null;

  boden_kalkgehalt?: string | null;

  boden_durchlaessigkeit?: string | null;

  boden_humus?: string | null;

  boden_naehrstoffgehalt?: string | null;

  boden_abtrag?: string | null;

  wasserhaushalt?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/**
 * Represents the mutator for the table apflora.tpop_history
 * @foreignKey (pop_id) references pop (id)\n@foreignKey (status) references pop_status_werte (code)\n@foreignKey (apber_relevant_grund) references tpop_apberrelevant_grund_werte (code)\n@foreignKey (ekfrequenz) references ekfrequenz (id)\n@foreignKey (ekf_kontrolleur) references adresse (id)
 */
export interface TpopHistoryMutator {
  /** Jahr: tpop_history wurde beim Erstellen des Jahresberichts im Februar des Folgejahrs von tpop kopiert */
  year?: ApHistoryYear;

  /** Primärschlüssel der Tabelle tpop */
  id?: TpopHistoryId;

  pop_id?: PopHistoryId | null;

  nr?: number | null;

  gemeinde?: string | null;

  flurname?: string | null;

  geom_point?: unknown | null;

  radius?: number | null;

  hoehe?: number | null;

  exposition?: string | null;

  klima?: string | null;

  neigung?: string | null;

  beschreibung?: string | null;

  kataster_nr?: string | null;

  status?: number | null;

  status_unklar?: boolean | null;

  status_unklar_grund?: string | null;

  apber_relevant?: boolean | null;

  apber_relevant_grund?: number | null;

  bekannt_seit?: number | null;

  eigentuemer?: string | null;

  kontakt?: string | null;

  nutzungszone?: string | null;

  bewirtschafter?: string | null;

  bewirtschaftung?: string | null;

  ekfrequenz?: string | null;

  ekfrequenz_startjahr?: number | null;

  ekfrequenz_abweichend?: boolean | null;

  ekf_kontrolleur?: string | null;

  bemerkungen?: string | null;

  changed_by?: string | null;

  boden_typ?: string | null;

  boden_kalkgehalt?: string | null;

  boden_durchlaessigkeit?: string | null;

  boden_humus?: string | null;

  boden_naehrstoffgehalt?: string | null;

  boden_abtrag?: string | null;

  wasserhaushalt?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
