// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface tpopmassn_pop_nr_params {
  tpopmassn: unknown;
}

/** Return type for tpopmassn_pop_nr */
export type tpopmassn_pop_nr_return_type = number;
