// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.tpop_outside_zh_for_ap */
export default interface TpopOutsideZhForAp {
  proj_id: string | null;

  ap_id: string | null;

  pop_id: string | null;

  pop_nr: number | null;

  id: string | null;

  nr: number | null;
}
