// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopmassnId } from './Tpopmassn';

/** Identifier type for apflora.tpopmassn_file */
export type TpopmassnFileId = string & { __brand: 'apflora.tpopmassn_file' };

/** Represents the table apflora.tpopmassn_file */
export default interface TpopmassnFile {
  id: TpopmassnFileId;

  tpopmassn_id: TpopmassnId | null;

  file_id: string | null;

  file_mime_type: string | null;

  name: string | null;

  beschreibung: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpopmassn_file */
export interface TpopmassnFileInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: TpopmassnFileId;

  tpopmassn_id?: TpopmassnId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpopmassn_file */
export interface TpopmassnFileMutator {
  id?: TpopmassnFileId;

  tpopmassn_id?: TpopmassnId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
