// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopId } from './Tpop';
import type { AdresseId } from './Adresse';

/** Identifier type for apflora.tpopmassn */
export type TpopmassnId = string & { __brand: 'apflora.tpopmassn' };

/**
 * Represents the table apflora.tpopmassn
 * (tpop_id) references tpop_history (id)
 */
export default interface Tpopmassn {
  id: TpopmassnId;

  /** Typ der Massnahme. Auswahl aus Tabelle "tpopmassn_typ_werte" */
  typ: number | null;

  /** Was wurde gemacht? V.a. für Typ "Spezial" */
  beschreibung: string | null;

  /** Jahr, in dem die Massnahme durchgeführt wurde */
  jahr: number | null;

  /** Datum, an dem die Massnahme durchgeführt wurde */
  datum: Date | null;

  /** Bemerkungen zur Massnahme */
  bemerkungen: string | null;

  /** Bezeichnung auf dem Plan */
  plan_bezeichnung: string | null;

  /** Fläche der Massnahme bzw. Teilpopulation (m2) */
  flaeche: number | null;

  /** Markierung der Massnahme bzw. Teilpopulation */
  markierung: string | null;

  /** Anzahl angesiedelte Triebe */
  anz_triebe: number | null;

  /** Anzahl angesiedelte Pflanzen */
  anz_pflanzen: number | null;

  /** Anzahl Töpfe/Pflanzstellen */
  anz_pflanzstellen: number | null;

  /** Wirtspflanze */
  wirtspflanze: string | null;

  /** Aus welcher Population stammt das Pflanzenmaterial? */
  herkunft_pop: string | null;

  /** Datum, an dem die angesiedelten Pflanzen gesammelt wurden */
  sammeldatum: string | null;

  /** Form, Grösse der Ansiedlung */
  form: string | null;

  /** Anordnung der Pflanzung */
  pflanzanordnung: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id: TpopId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter: AdresseId | null;

  /** Existiert ein Plan? */
  plan_vorhanden: boolean | null;

  /** Gezählte Zieleinheit */
  zieleinheit_einheit: number | null;

  /** Anzahl Zieleinheiten */
  zieleinheit_anzahl: number | null;

  /** Anzahl besammelte Individuen der Herkunftspopulation */
  von_anzahl_individuen: number | null;

  created_at: Date;

  updated_at: Date;
}

/**
 * Represents the initializer for the table apflora.tpopmassn
 * (tpop_id) references tpop_history (id)
 */
export interface TpopmassnInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: TpopmassnId;

  /** Typ der Massnahme. Auswahl aus Tabelle "tpopmassn_typ_werte" */
  typ?: number | null;

  /** Was wurde gemacht? V.a. für Typ "Spezial" */
  beschreibung?: string | null;

  /** Jahr, in dem die Massnahme durchgeführt wurde */
  jahr?: number | null;

  /** Datum, an dem die Massnahme durchgeführt wurde */
  datum?: Date | null;

  /** Bemerkungen zur Massnahme */
  bemerkungen?: string | null;

  /** Bezeichnung auf dem Plan */
  plan_bezeichnung?: string | null;

  /** Fläche der Massnahme bzw. Teilpopulation (m2) */
  flaeche?: number | null;

  /** Markierung der Massnahme bzw. Teilpopulation */
  markierung?: string | null;

  /** Anzahl angesiedelte Triebe */
  anz_triebe?: number | null;

  /** Anzahl angesiedelte Pflanzen */
  anz_pflanzen?: number | null;

  /** Anzahl Töpfe/Pflanzstellen */
  anz_pflanzstellen?: number | null;

  /** Wirtspflanze */
  wirtspflanze?: string | null;

  /** Aus welcher Population stammt das Pflanzenmaterial? */
  herkunft_pop?: string | null;

  /**
   * Datum, an dem die angesiedelten Pflanzen gesammelt wurden
   * Default value: NULL::character varying
   */
  sammeldatum?: string | null;

  /** Form, Grösse der Ansiedlung */
  form?: string | null;

  /** Anordnung der Pflanzung */
  pflanzanordnung?: string | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id?: TpopId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter?: AdresseId | null;

  /**
   * Existiert ein Plan?
   * Default value: false
   */
  plan_vorhanden?: boolean | null;

  /** Gezählte Zieleinheit */
  zieleinheit_einheit?: number | null;

  /** Anzahl Zieleinheiten */
  zieleinheit_anzahl?: number | null;

  /** Anzahl besammelte Individuen der Herkunftspopulation */
  von_anzahl_individuen?: number | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/**
 * Represents the mutator for the table apflora.tpopmassn
 * (tpop_id) references tpop_history (id)
 */
export interface TpopmassnMutator {
  id?: TpopmassnId;

  /** Typ der Massnahme. Auswahl aus Tabelle "tpopmassn_typ_werte" */
  typ?: number | null;

  /** Was wurde gemacht? V.a. für Typ "Spezial" */
  beschreibung?: string | null;

  /** Jahr, in dem die Massnahme durchgeführt wurde */
  jahr?: number | null;

  /** Datum, an dem die Massnahme durchgeführt wurde */
  datum?: Date | null;

  /** Bemerkungen zur Massnahme */
  bemerkungen?: string | null;

  /** Bezeichnung auf dem Plan */
  plan_bezeichnung?: string | null;

  /** Fläche der Massnahme bzw. Teilpopulation (m2) */
  flaeche?: number | null;

  /** Markierung der Massnahme bzw. Teilpopulation */
  markierung?: string | null;

  /** Anzahl angesiedelte Triebe */
  anz_triebe?: number | null;

  /** Anzahl angesiedelte Pflanzen */
  anz_pflanzen?: number | null;

  /** Anzahl Töpfe/Pflanzstellen */
  anz_pflanzstellen?: number | null;

  /** Wirtspflanze */
  wirtspflanze?: string | null;

  /** Aus welcher Population stammt das Pflanzenmaterial? */
  herkunft_pop?: string | null;

  /** Datum, an dem die angesiedelten Pflanzen gesammelt wurden */
  sammeldatum?: string | null;

  /** Form, Grösse der Ansiedlung */
  form?: string | null;

  /** Anordnung der Pflanzung */
  pflanzanordnung?: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id?: TpopId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter?: AdresseId | null;

  /** Existiert ein Plan? */
  plan_vorhanden?: boolean | null;

  /** Gezählte Zieleinheit */
  zieleinheit_einheit?: number | null;

  /** Anzahl Zieleinheiten */
  zieleinheit_anzahl?: number | null;

  /** Anzahl besammelte Individuen der Herkunftspopulation */
  von_anzahl_individuen?: number | null;

  created_at?: Date;

  updated_at?: Date;
}
