// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopId } from './Tpop';
import type { AdresseId } from './Adresse';

/** Identifier type for apflora.tpopkontr */
export type TpopkontrId = string & { __brand: 'apflora.tpopkontr' };

/** Represents the table apflora.tpopkontr */
export default interface Tpopkontr {
  /** Primärschlüssel. Wird u.a. verwendet für die Identifikation der Beobachtung im nationalen Beobachtungs-Daten-Kreislauf */
  id: TpopkontrId;

  /** Typ der Kontrolle. Auswahl aus Tabelle "tpopkontr_typ_werte" */
  typ: string | null;

  /** Wann wurde kontrolliert? */
  datum: Date | null;

  /** In welchem Jahr wurde kontrolliert? Für welches Jahr gilt die Beschreibung? */
  jahr: number | null;

  /** Vitalität der Pflanzen */
  vitalitaet: string | null;

  /** Überlebensrate in Prozent */
  ueberlebensrate: number | null;

  /** Entwicklung des Bestandes. Auswahl aus Tabelle "tpop_entwicklung_werte" */
  entwicklung: number | null;

  /** Ursachen der Entwicklung */
  ursachen: string | null;

  /** Erfolgsbeurteilung */
  erfolgsbeurteilung: string | null;

  /** Vorschlag für Änderung der Umsetzung */
  umsetzung_aendern: string | null;

  /** Vorschlag für Änderung der Erfolgskontrolle */
  kontrolle_aendern: string | null;

  /** Bemerkungen zur Erfolgskontrolle */
  bemerkungen: string | null;

  /** Lebensraumtyp nach Delarze */
  lr_delarze: string | null;

  /** Fläche der Teilpopulation */
  flaeche: number | null;

  /** Lebensraumtyp der direkt angrenzenden Umgebung (nach Delarze) */
  lr_umgebung_delarze: string | null;

  /** Vegetationstyp */
  vegetationstyp: string | null;

  /** Konkurrenz */
  konkurrenz: string | null;

  /** Moosschicht */
  moosschicht: string | null;

  /** Krautschicht */
  krautschicht: string | null;

  /** Strauchschicht, ehemals Verbuschung (%) */
  strauchschicht: string | null;

  /** Baumschicht */
  baumschicht: string | null;

  /** Übereinstimmung mit dem Idealbiotop */
  idealbiotop_uebereinstimmung: number | null;

  /** Handlungsbedarf bezüglich Biotop */
  handlungsbedarf: string | null;

  /** Überprüfte Fläche in m2. Nur für Freiwilligen-Erfolgskontrolle */
  flaeche_ueberprueft: number | null;

  /** Von Pflanzen, Streu oder Moos bedeckter Boden (%). Nur für Freiwilligen-Erfolgskontrolle. Nur bis 2012 erfasst. */
  deckung_vegetation: number | null;

  /** Flächenanteil nackter Boden (%). Nur für Freiwilligen-Erfolgskontrolle */
  deckung_nackter_boden: number | null;

  /** Flächenanteil der überprüften Pflanzenart (%). Nur für Freiwilligen-Erfolgskontrolle */
  deckung_ap_art: number | null;

  /** Maximale Vegetationshöhe in cm. Nur für Freiwilligen-Erfolgskontrolle */
  vegetationshoehe_maximum: number | null;

  /** Mittlere Vegetationshöhe in cm. Nur für Freiwilligen-Erfolgskontrolle */
  vegetationshoehe_mittel: number | null;

  /** Gefährdung. Nur für Freiwilligen-Erfolgskontrolle */
  gefaehrdung: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id: TpopId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter: AdresseId | null;

  /** Fläche / Wuchsort auf Plan eingezeichnet? Nur für Freiwilligen-Erfolgskontrolle */
  plan_vorhanden: boolean | null;

  /** Gibt es neben alten Pflanzen auch junge? Nur für Freiwilligen-Erfolgskontrolle */
  jungpflanzen_vorhanden: boolean | null;

  ekf_bemerkungen: string | null;

  /** Pro Jahr sollte maximal eine Kontrolle AP-Bericht-relevant sein. Dient dazu Kontrollen auszuschliessen */
  apber_nicht_relevant: boolean | null;

  /** Grund, wieso die Kontrolle vom AP-Bericht ausgeschlossen wurde */
  apber_nicht_relevant_grund: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpopkontr */
export interface TpopkontrInitializer {
  /**
   * Primärschlüssel. Wird u.a. verwendet für die Identifikation der Beobachtung im nationalen Beobachtungs-Daten-Kreislauf
   * Default value: uuid_generate_v1mc()
   */
  id?: TpopkontrId;

  /**
   * Typ der Kontrolle. Auswahl aus Tabelle "tpopkontr_typ_werte"
   * Default value: NULL::character varying
   */
  typ?: string | null;

  /** Wann wurde kontrolliert? */
  datum?: Date | null;

  /** In welchem Jahr wurde kontrolliert? Für welches Jahr gilt die Beschreibung? */
  jahr?: number | null;

  /** Vitalität der Pflanzen */
  vitalitaet?: string | null;

  /** Überlebensrate in Prozent */
  ueberlebensrate?: number | null;

  /** Entwicklung des Bestandes. Auswahl aus Tabelle "tpop_entwicklung_werte" */
  entwicklung?: number | null;

  /** Ursachen der Entwicklung */
  ursachen?: string | null;

  /** Erfolgsbeurteilung */
  erfolgsbeurteilung?: string | null;

  /** Vorschlag für Änderung der Umsetzung */
  umsetzung_aendern?: string | null;

  /** Vorschlag für Änderung der Erfolgskontrolle */
  kontrolle_aendern?: string | null;

  /** Bemerkungen zur Erfolgskontrolle */
  bemerkungen?: string | null;

  /** Lebensraumtyp nach Delarze */
  lr_delarze?: string | null;

  /** Fläche der Teilpopulation */
  flaeche?: number | null;

  /** Lebensraumtyp der direkt angrenzenden Umgebung (nach Delarze) */
  lr_umgebung_delarze?: string | null;

  /**
   * Vegetationstyp
   * Default value: NULL::character varying
   */
  vegetationstyp?: string | null;

  /**
   * Konkurrenz
   * Default value: NULL::character varying
   */
  konkurrenz?: string | null;

  /**
   * Moosschicht
   * Default value: NULL::character varying
   */
  moosschicht?: string | null;

  /**
   * Krautschicht
   * Default value: NULL::character varying
   */
  krautschicht?: string | null;

  /** Strauchschicht, ehemals Verbuschung (%) */
  strauchschicht?: string | null;

  /**
   * Baumschicht
   * Default value: NULL::character varying
   */
  baumschicht?: string | null;

  /** Übereinstimmung mit dem Idealbiotop */
  idealbiotop_uebereinstimmung?: number | null;

  /** Handlungsbedarf bezüglich Biotop */
  handlungsbedarf?: string | null;

  /** Überprüfte Fläche in m2. Nur für Freiwilligen-Erfolgskontrolle */
  flaeche_ueberprueft?: number | null;

  /** Von Pflanzen, Streu oder Moos bedeckter Boden (%). Nur für Freiwilligen-Erfolgskontrolle. Nur bis 2012 erfasst. */
  deckung_vegetation?: number | null;

  /** Flächenanteil nackter Boden (%). Nur für Freiwilligen-Erfolgskontrolle */
  deckung_nackter_boden?: number | null;

  /** Flächenanteil der überprüften Pflanzenart (%). Nur für Freiwilligen-Erfolgskontrolle */
  deckung_ap_art?: number | null;

  /** Maximale Vegetationshöhe in cm. Nur für Freiwilligen-Erfolgskontrolle */
  vegetationshoehe_maximum?: number | null;

  /** Mittlere Vegetationshöhe in cm. Nur für Freiwilligen-Erfolgskontrolle */
  vegetationshoehe_mittel?: number | null;

  /** Gefährdung. Nur für Freiwilligen-Erfolgskontrolle */
  gefaehrdung?: string | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id?: TpopId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter?: AdresseId | null;

  /**
   * Fläche / Wuchsort auf Plan eingezeichnet? Nur für Freiwilligen-Erfolgskontrolle
   * Default value: false
   */
  plan_vorhanden?: boolean | null;

  /** Gibt es neben alten Pflanzen auch junge? Nur für Freiwilligen-Erfolgskontrolle */
  jungpflanzen_vorhanden?: boolean | null;

  ekf_bemerkungen?: string | null;

  /** Pro Jahr sollte maximal eine Kontrolle AP-Bericht-relevant sein. Dient dazu Kontrollen auszuschliessen */
  apber_nicht_relevant?: boolean | null;

  /** Grund, wieso die Kontrolle vom AP-Bericht ausgeschlossen wurde */
  apber_nicht_relevant_grund?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpopkontr */
export interface TpopkontrMutator {
  /** Primärschlüssel. Wird u.a. verwendet für die Identifikation der Beobachtung im nationalen Beobachtungs-Daten-Kreislauf */
  id?: TpopkontrId;

  /** Typ der Kontrolle. Auswahl aus Tabelle "tpopkontr_typ_werte" */
  typ?: string | null;

  /** Wann wurde kontrolliert? */
  datum?: Date | null;

  /** In welchem Jahr wurde kontrolliert? Für welches Jahr gilt die Beschreibung? */
  jahr?: number | null;

  /** Vitalität der Pflanzen */
  vitalitaet?: string | null;

  /** Überlebensrate in Prozent */
  ueberlebensrate?: number | null;

  /** Entwicklung des Bestandes. Auswahl aus Tabelle "tpop_entwicklung_werte" */
  entwicklung?: number | null;

  /** Ursachen der Entwicklung */
  ursachen?: string | null;

  /** Erfolgsbeurteilung */
  erfolgsbeurteilung?: string | null;

  /** Vorschlag für Änderung der Umsetzung */
  umsetzung_aendern?: string | null;

  /** Vorschlag für Änderung der Erfolgskontrolle */
  kontrolle_aendern?: string | null;

  /** Bemerkungen zur Erfolgskontrolle */
  bemerkungen?: string | null;

  /** Lebensraumtyp nach Delarze */
  lr_delarze?: string | null;

  /** Fläche der Teilpopulation */
  flaeche?: number | null;

  /** Lebensraumtyp der direkt angrenzenden Umgebung (nach Delarze) */
  lr_umgebung_delarze?: string | null;

  /** Vegetationstyp */
  vegetationstyp?: string | null;

  /** Konkurrenz */
  konkurrenz?: string | null;

  /** Moosschicht */
  moosschicht?: string | null;

  /** Krautschicht */
  krautschicht?: string | null;

  /** Strauchschicht, ehemals Verbuschung (%) */
  strauchschicht?: string | null;

  /** Baumschicht */
  baumschicht?: string | null;

  /** Übereinstimmung mit dem Idealbiotop */
  idealbiotop_uebereinstimmung?: number | null;

  /** Handlungsbedarf bezüglich Biotop */
  handlungsbedarf?: string | null;

  /** Überprüfte Fläche in m2. Nur für Freiwilligen-Erfolgskontrolle */
  flaeche_ueberprueft?: number | null;

  /** Von Pflanzen, Streu oder Moos bedeckter Boden (%). Nur für Freiwilligen-Erfolgskontrolle. Nur bis 2012 erfasst. */
  deckung_vegetation?: number | null;

  /** Flächenanteil nackter Boden (%). Nur für Freiwilligen-Erfolgskontrolle */
  deckung_nackter_boden?: number | null;

  /** Flächenanteil der überprüften Pflanzenart (%). Nur für Freiwilligen-Erfolgskontrolle */
  deckung_ap_art?: number | null;

  /** Maximale Vegetationshöhe in cm. Nur für Freiwilligen-Erfolgskontrolle */
  vegetationshoehe_maximum?: number | null;

  /** Mittlere Vegetationshöhe in cm. Nur für Freiwilligen-Erfolgskontrolle */
  vegetationshoehe_mittel?: number | null;

  /** Gefährdung. Nur für Freiwilligen-Erfolgskontrolle */
  gefaehrdung?: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id?: TpopId | null;

  /** Zugehöriger Bearbeiter. Fremdschlüssel aus der Tabelle "adresse" */
  bearbeiter?: AdresseId | null;

  /** Fläche / Wuchsort auf Plan eingezeichnet? Nur für Freiwilligen-Erfolgskontrolle */
  plan_vorhanden?: boolean | null;

  /** Gibt es neben alten Pflanzen auch junge? Nur für Freiwilligen-Erfolgskontrolle */
  jungpflanzen_vorhanden?: boolean | null;

  ekf_bemerkungen?: string | null;

  /** Pro Jahr sollte maximal eine Kontrolle AP-Bericht-relevant sein. Dient dazu Kontrollen auszuschliessen */
  apber_nicht_relevant?: boolean | null;

  /** Grund, wieso die Kontrolle vom AP-Bericht ausgeschlossen wurde */
  apber_nicht_relevant_grund?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
