// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType apflora.tpop_kontrolliert_for_jber */
export default interface TpopKontrolliertForJber {
  year: number | null;

  anz_tpop: string | null;

  anz_tpopber: string | null;
}
