// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopkontrId } from './Tpopkontr';

/** Identifier type for apflora.tpopkontrzaehl */
export type TpopkontrzaehlId = string & { __brand: 'apflora.tpopkontrzaehl' };

/** Represents the table apflora.tpopkontrzaehl */
export default interface Tpopkontrzaehl {
  id: TpopkontrzaehlId;

  /** Anzahl Zaehleinheiten */
  anzahl: number | null;

  /** Verwendete Zaehleinheit. Auswahl aus Tabelle "tpopkontrzaehl_einheit_werte" */
  einheit: number | null;

  /** Verwendete Methodik. Auswahl aus Tabelle "tpopkontrzaehl_methode_werte" */
  methode: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  tpopkontr_id: TpopkontrId | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpopkontrzaehl */
export interface TpopkontrzaehlInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: TpopkontrzaehlId;

  /** Anzahl Zaehleinheiten */
  anzahl?: number | null;

  /** Verwendete Zaehleinheit. Auswahl aus Tabelle "tpopkontrzaehl_einheit_werte" */
  einheit?: number | null;

  /** Verwendete Methodik. Auswahl aus Tabelle "tpopkontrzaehl_methode_werte" */
  methode?: number | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  tpopkontr_id?: TpopkontrId | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpopkontrzaehl */
export interface TpopkontrzaehlMutator {
  id?: TpopkontrzaehlId;

  /** Anzahl Zaehleinheiten */
  anzahl?: number | null;

  /** Verwendete Zaehleinheit. Auswahl aus Tabelle "tpopkontrzaehl_einheit_werte" */
  einheit?: number | null;

  /** Verwendete Methodik. Auswahl aus Tabelle "tpopkontrzaehl_methode_werte" */
  methode?: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  tpopkontr_id?: TpopkontrId | null;

  created_at?: Date;

  updated_at?: Date;
}
