// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopId } from './Tpop';

/** Identifier type for apflora.tpop_file */
export type TpopFileId = string & { __brand: 'apflora.tpop_file' };

/** Represents the table apflora.tpop_file */
export default interface TpopFile {
  id: TpopFileId;

  tpop_id: TpopId | null;

  file_id: string | null;

  file_mime_type: string | null;

  name: string | null;

  beschreibung: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpop_file */
export interface TpopFileInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: TpopFileId;

  tpop_id?: TpopId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpop_file */
export interface TpopFileMutator {
  id?: TpopFileId;

  tpop_id?: TpopId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
