// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopkontrId } from './Tpopkontr';

/** Identifier type for apflora.tpopkontr_file */
export type TpopkontrFileId = string & { __brand: 'apflora.tpopkontr_file' };

/** Represents the table apflora.tpopkontr_file */
export default interface TpopkontrFile {
  id: TpopkontrFileId;

  tpopkontr_id: TpopkontrId | null;

  file_id: string | null;

  file_mime_type: string | null;

  name: string | null;

  beschreibung: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpopkontr_file */
export interface TpopkontrFileInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: TpopkontrFileId;

  tpopkontr_id?: TpopkontrId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpopkontr_file */
export interface TpopkontrFileMutator {
  id?: TpopkontrFileId;

  tpopkontr_id?: TpopkontrId | null;

  file_id?: string | null;

  file_mime_type?: string | null;

  name?: string | null;

  beschreibung?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
