// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.tpopmassn_erfbeurt_werte */
export type TpopmassnErfbeurtWerteId = string & { __brand: 'apflora.tpopmassn_erfbeurt_werte' };

/** Represents the table apflora.tpopmassn_erfbeurt_werte */
export default interface TpopmassnErfbeurtWerte {
  /** Primärschlüssel */
  id: TpopmassnErfbeurtWerteId;

  code: number | null;

  /** Wie werden die durchgefuehrten Massnahmen beurteilt? */
  text: string | null;

  sort: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic: boolean | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpopmassn_erfbeurt_werte */
export interface TpopmassnErfbeurtWerteInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: TpopmassnErfbeurtWerteId;

  /** Default value: nextval('apflora.tpopmassn_erfbeurt_werte_code_seq'::regclass) */
  code?: number | null;

  /**
   * Wie werden die durchgefuehrten Massnahmen beurteilt?
   * Default value: NULL::character varying
   */
  text?: string | null;

  sort?: number | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /**
   * Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten
   * Default value: false
   */
  historic?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpopmassn_erfbeurt_werte */
export interface TpopmassnErfbeurtWerteMutator {
  /** Primärschlüssel */
  id?: TpopmassnErfbeurtWerteId;

  code?: number | null;

  /** Wie werden die durchgefuehrten Massnahmen beurteilt? */
  text?: string | null;

  sort?: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic?: boolean | null;

  created_at?: Date;

  updated_at?: Date;
}
