// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface tpopkontr_pop_nr_params {
  tpopkontr: unknown;
}

/** Return type for tpopkontr_pop_nr */
export type tpopkontr_pop_nr_return_type = number;
