// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopId } from './Tpop';

/** Identifier type for apflora.tpopmassnber */
export type TpopmassnberId = string & { __brand: 'apflora.tpopmassnber' };

/** Represents the table apflora.tpopmassnber */
export default interface Tpopmassnber {
  id: TpopmassnberId;

  /** Jahr, für den der Bericht gilt */
  jahr: number | null;

  /** Beurteilung des Erfolgs. Auswahl aus Tabelle "tpopmassn_erfbeurt_werte" */
  beurteilung: number | null;

  /** Bemerkungen zur Beurteilung */
  bemerkungen: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id: TpopId | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpopmassnber */
export interface TpopmassnberInitializer {
  /** Default value: uuid_generate_v1mc() */
  id?: TpopmassnberId;

  /** Jahr, für den der Bericht gilt */
  jahr?: number | null;

  /** Beurteilung des Erfolgs. Auswahl aus Tabelle "tpopmassn_erfbeurt_werte" */
  beurteilung?: number | null;

  /** Bemerkungen zur Beurteilung */
  bemerkungen?: string | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id?: TpopId | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpopmassnber */
export interface TpopmassnberMutator {
  id?: TpopmassnberId;

  /** Jahr, für den der Bericht gilt */
  jahr?: number | null;

  /** Beurteilung des Erfolgs. Auswahl aus Tabelle "tpopmassn_erfbeurt_werte" */
  beurteilung?: number | null;

  /** Bemerkungen zur Beurteilung */
  bemerkungen?: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Zugehörige Teilpopulation. Fremdschlüssel der Tabelle "tpop" */
  tpop_id?: TpopId | null;

  created_at?: Date;

  updated_at?: Date;
}
