// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PopId } from './Pop';
import type { EkfrequenzId } from './Ekfrequenz';
import type { AdresseId } from './Adresse';

/** Identifier type for apflora.tpop */
export type TpopId = string & { __brand: 'apflora.tpop' };

/** Represents the table apflora.tpop */
export default interface Tpop {
  /** Primärschlüssel */
  id: TpopId;

  /** Nummer der Teilpopulation */
  nr: number | null;

  /** Gemeinde */
  gemeinde: string | null;

  /** Flurname */
  flurname: string | null;

  /** Radius der Teilpopulation (m) */
  radius: number | null;

  /** Höhe über Meer (m) */
  hoehe: number | null;

  /** Exposition / Besonnung des Standorts */
  exposition: string | null;

  /** Klima des Standorts */
  klima: string | null;

  /** Hangneigung des Standorts */
  neigung: string | null;

  /** Beschreibung der Fläche */
  beschreibung: string | null;

  /** Kataster-Nummer */
  kataster_nr: string | null;

  /** Herkunft der Teilpopulation. Auswahl aus Tabelle "pop_status_werte" */
  status: number | null;

  /** Wieso ist der Status unklar? */
  status_unklar_grund: string | null;

  /** Seit wann ist die Teilpopulation bekannt? */
  bekannt_seit: number | null;

  /** EigentümerIn */
  eigentuemer: string | null;

  /** Kontaktperson vor Ort */
  kontakt: string | null;

  /** Nutzungszone */
  nutzungszone: string | null;

  /** Wer bewirtschaftet die Fläche? */
  bewirtschafter: string | null;

  /** Wie wird die Fläche bewirtschaftet? */
  bewirtschaftung: string | null;

  /** Bemerkungen zur Teilpopulation */
  bemerkungen: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Zugehörige Population. Fremdschlüssel aus der Tabelle "pop" */
  pop_id: PopId | null;

  /** Ist der Status der Teilpopulation unklar? (es bestehen keine glaubwuerdigen Beboachtungen) */
  status_unklar: boolean | null;

  apber_relevant: boolean | null;

  /** Grund für AP-Bericht Relevanz. Auswahl aus der Tabelle "tpop_apberrelevant_grund_werte" */
  apber_relevant_grund: number | null;

  geom_point: unknown | null;

  /** Wert aus Tabelle ekfrequenz. Bestimmt, wie häufig kontrolliert werden soll */
  ekfrequenz: EkfrequenzId | null;

  /** Wer diese TPop freiwillig kontrolliert. Dient dazu, Formulare für die EKF zu generieren */
  ekfrequenz_abweichend: boolean | null;

  /** Das Basisjahr, von dem aus ekpläne gemäss eqfrequenz gesetzt werden */
  ekfrequenz_startjahr: number | null;

  ekf_kontrolleur: AdresseId | null;

  /** Bodentyp */
  boden_typ: string | null;

  /** Kalkgehalt des Bodens */
  boden_kalkgehalt: string | null;

  /** Durchlässigkeit des Bodens */
  boden_durchlaessigkeit: string | null;

  /** Humusgehalt des Bodens */
  boden_humus: string | null;

  /** Nährstoffgehalt des Bodens */
  boden_naehrstoffgehalt: string | null;

  /** Oberbodenabtrag */
  boden_abtrag: string | null;

  /** Wasserhaushalt */
  wasserhaushalt: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpop */
export interface TpopInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: TpopId;

  /** Nummer der Teilpopulation */
  nr?: number | null;

  /** Gemeinde */
  gemeinde?: string | null;

  /** Flurname */
  flurname?: string | null;

  /** Radius der Teilpopulation (m) */
  radius?: number | null;

  /** Höhe über Meer (m) */
  hoehe?: number | null;

  /**
   * Exposition / Besonnung des Standorts
   * Default value: NULL::character varying
   */
  exposition?: string | null;

  /**
   * Klima des Standorts
   * Default value: NULL::character varying
   */
  klima?: string | null;

  /**
   * Hangneigung des Standorts
   * Default value: NULL::character varying
   */
  neigung?: string | null;

  /** Beschreibung der Fläche */
  beschreibung?: string | null;

  /** Kataster-Nummer */
  kataster_nr?: string | null;

  /** Herkunft der Teilpopulation. Auswahl aus Tabelle "pop_status_werte" */
  status?: number | null;

  /** Wieso ist der Status unklar? */
  status_unklar_grund?: string | null;

  /** Seit wann ist die Teilpopulation bekannt? */
  bekannt_seit?: number | null;

  /** EigentümerIn */
  eigentuemer?: string | null;

  /** Kontaktperson vor Ort */
  kontakt?: string | null;

  /** Nutzungszone */
  nutzungszone?: string | null;

  /** Wer bewirtschaftet die Fläche? */
  bewirtschafter?: string | null;

  /** Wie wird die Fläche bewirtschaftet? */
  bewirtschaftung?: string | null;

  /** Bemerkungen zur Teilpopulation */
  bemerkungen?: string | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Zugehörige Population. Fremdschlüssel aus der Tabelle "pop" */
  pop_id?: PopId | null;

  /**
   * Ist der Status der Teilpopulation unklar? (es bestehen keine glaubwuerdigen Beboachtungen)
   * Default value: false
   */
  status_unklar?: boolean | null;

  /** Default value: true */
  apber_relevant?: boolean | null;

  /** Grund für AP-Bericht Relevanz. Auswahl aus der Tabelle "tpop_apberrelevant_grund_werte" */
  apber_relevant_grund?: number | null;

  geom_point?: unknown | null;

  /** Wert aus Tabelle ekfrequenz. Bestimmt, wie häufig kontrolliert werden soll */
  ekfrequenz?: EkfrequenzId | null;

  /**
   * Wer diese TPop freiwillig kontrolliert. Dient dazu, Formulare für die EKF zu generieren
   * Default value: false
   */
  ekfrequenz_abweichend?: boolean | null;

  /** Das Basisjahr, von dem aus ekpläne gemäss eqfrequenz gesetzt werden */
  ekfrequenz_startjahr?: number | null;

  ekf_kontrolleur?: AdresseId | null;

  /** Bodentyp */
  boden_typ?: string | null;

  /** Kalkgehalt des Bodens */
  boden_kalkgehalt?: string | null;

  /** Durchlässigkeit des Bodens */
  boden_durchlaessigkeit?: string | null;

  /** Humusgehalt des Bodens */
  boden_humus?: string | null;

  /** Nährstoffgehalt des Bodens */
  boden_naehrstoffgehalt?: string | null;

  /** Oberbodenabtrag */
  boden_abtrag?: string | null;

  /** Wasserhaushalt */
  wasserhaushalt?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpop */
export interface TpopMutator {
  /** Primärschlüssel */
  id?: TpopId;

  /** Nummer der Teilpopulation */
  nr?: number | null;

  /** Gemeinde */
  gemeinde?: string | null;

  /** Flurname */
  flurname?: string | null;

  /** Radius der Teilpopulation (m) */
  radius?: number | null;

  /** Höhe über Meer (m) */
  hoehe?: number | null;

  /** Exposition / Besonnung des Standorts */
  exposition?: string | null;

  /** Klima des Standorts */
  klima?: string | null;

  /** Hangneigung des Standorts */
  neigung?: string | null;

  /** Beschreibung der Fläche */
  beschreibung?: string | null;

  /** Kataster-Nummer */
  kataster_nr?: string | null;

  /** Herkunft der Teilpopulation. Auswahl aus Tabelle "pop_status_werte" */
  status?: number | null;

  /** Wieso ist der Status unklar? */
  status_unklar_grund?: string | null;

  /** Seit wann ist die Teilpopulation bekannt? */
  bekannt_seit?: number | null;

  /** EigentümerIn */
  eigentuemer?: string | null;

  /** Kontaktperson vor Ort */
  kontakt?: string | null;

  /** Nutzungszone */
  nutzungszone?: string | null;

  /** Wer bewirtschaftet die Fläche? */
  bewirtschafter?: string | null;

  /** Wie wird die Fläche bewirtschaftet? */
  bewirtschaftung?: string | null;

  /** Bemerkungen zur Teilpopulation */
  bemerkungen?: string | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Zugehörige Population. Fremdschlüssel aus der Tabelle "pop" */
  pop_id?: PopId | null;

  /** Ist der Status der Teilpopulation unklar? (es bestehen keine glaubwuerdigen Beboachtungen) */
  status_unklar?: boolean | null;

  apber_relevant?: boolean | null;

  /** Grund für AP-Bericht Relevanz. Auswahl aus der Tabelle "tpop_apberrelevant_grund_werte" */
  apber_relevant_grund?: number | null;

  geom_point?: unknown | null;

  /** Wert aus Tabelle ekfrequenz. Bestimmt, wie häufig kontrolliert werden soll */
  ekfrequenz?: EkfrequenzId | null;

  /** Wer diese TPop freiwillig kontrolliert. Dient dazu, Formulare für die EKF zu generieren */
  ekfrequenz_abweichend?: boolean | null;

  /** Das Basisjahr, von dem aus ekpläne gemäss eqfrequenz gesetzt werden */
  ekfrequenz_startjahr?: number | null;

  ekf_kontrolleur?: AdresseId | null;

  /** Bodentyp */
  boden_typ?: string | null;

  /** Kalkgehalt des Bodens */
  boden_kalkgehalt?: string | null;

  /** Durchlässigkeit des Bodens */
  boden_durchlaessigkeit?: string | null;

  /** Humusgehalt des Bodens */
  boden_humus?: string | null;

  /** Nährstoffgehalt des Bodens */
  boden_naehrstoffgehalt?: string | null;

  /** Oberbodenabtrag */
  boden_abtrag?: string | null;

  /** Wasserhaushalt */
  wasserhaushalt?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
