// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.tpopmassn_typ_werte */
export type TpopmassnTypWerteId = string & { __brand: 'apflora.tpopmassn_typ_werte' };

/** Represents the table apflora.tpopmassn_typ_werte */
export default interface TpopmassnTypWerte {
  /** Primärschlüssel */
  id: TpopmassnTypWerteId;

  code: number | null;

  text: string | null;

  sort: number | null;

  /** Handelt es sich um eine Ansiedlung? */
  ansiedlung: boolean;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  anpflanzung: boolean | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic: boolean | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.tpopmassn_typ_werte */
export interface TpopmassnTypWerteInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: TpopmassnTypWerteId;

  /** Default value: nextval('apflora.tpopmassn_typ_werte_code_seq'::regclass) */
  code?: number | null;

  /** Default value: NULL::character varying */
  text?: string | null;

  sort?: number | null;

  /**
   * Handelt es sich um eine Ansiedlung?
   * Default value: false
   */
  ansiedlung?: boolean;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /** Default value: false */
  anpflanzung?: boolean | null;

  /**
   * Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten
   * Default value: false
   */
  historic?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.tpopmassn_typ_werte */
export interface TpopmassnTypWerteMutator {
  /** Primärschlüssel */
  id?: TpopmassnTypWerteId;

  code?: number | null;

  text?: string | null;

  sort?: number | null;

  /** Handelt es sich um eine Ansiedlung? */
  ansiedlung?: boolean;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  anpflanzung?: boolean | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic?: boolean | null;

  created_at?: Date;

  updated_at?: Date;
}
