// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_ae_tax_list */
export default interface VAeTaxList {
  taxonomie_id: string | null;

  taxonomie_name: string | null;
}
