// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';

/**
 * Represents the view apflora.v_ap_anzmassn
 * (id) references ap (id)
 */
export default interface VApAnzmassn {
  id: ApId;

  anzahl_massnahmen: string;
}
