// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';

/**
 * Represents the view apflora.v_ap_anzkontr
 * (id) references ap (id)
 */
export default interface VApAnzkontr {
  id: ApId;

  anzahl_kontrollen: string;
}
