// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';

/**
 * Represents the view apflora.v_ap_apberundmassn
 * (id) references ap (id)
 */
export default interface VApApberundmassn {
  id: ApId;

  massn_jahr: number;

  massn_anzahl: string;

  massn_anzahl_bisher: string;

  bericht_erstellt: string;
}
