// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_ap_ausw_pop_status */
export default interface VApAuswPopStatus {
  ap_id: string;

  jahr: number;

  values: unknown;
}
