// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_beob_nicht_zuzuordnen */
export default interface VBeobNichtZuzuordnen {
  id: string;

  quelle: string;

  id_field: string;

  OriginalId: string;

  art_id: string;

  art_id_original: string;

  Artname: string;

  pop_id: string;

  pop_nr: number;

  tpop_id: string;

  tpop_nr: number;

  tpop_status: string;

  tpop_gemeinde: string;

  tpop_flurname: string;

  x: number;

  y: number;

  distanz_zur_teilpopulation: number;

  datum: Date;

  autor: string;

  nicht_zuordnen: boolean;

  bemerkungen: string;

  created_at: Date;

  updated_at: Date;

  changed_by: string;
}
