// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_ek_planung_nach_abrechnungstyp */
export default interface VEkPlanungNachAbrechnungstyp {
  artname: string;

  ap_id: string;

  artverantwortlich: string;

  jahr: number;

  a: number;

  b: number;

  d: number;

  ekf: number;
}
