// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_export_info_flora_beob */
export default interface VExportInfoFloraBeob {
  id_projektintern: string;

  taxonomie_id: number;

  taxonomie: string;

  artname: string;

  beobachtungstyp: string;

  beobachtungstyp_codiert: string;

  herkunft: string;

  herkunft_codiert: string;

  status: string;

  bekannt_seit: number;

  datum: string;

  jahr: number;

  monat: number;

  tag: number;

  genauigkeit_datum: string;

  genauigkeit_datum_codiert: string;

  praesenz: string;

  praesenz_codiert: string;

  gefaehrdung: string;

  vitalitaet: string;

  beschreibung: string;

  lebensraum_nach_delarze: string;

  umgebung_nach_delarze: string;

  deckung_moosschicht: string;

  deckung_krautschicht: string;

  deckung_strauchschicht: string;

  deckung_baumschicht: string;

  genauigkeit_lage: string;

  genauigkeit_lage_codiert: string;

  geometry_type: string;

  genauigkeit_hoehe: string;

  x: number;

  y: number;

  gemeinde: string;

  flurname: string;

  obergrenze_hoehe: number;

  zaehlungen: string;

  expertise_introduit: string;

  expertise_introduite_nom: string;

  projekt: string;

  autor: string;

  aktionsplan: string;
}
