// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_kontrzaehl_anzproeinheit */
export default interface VKontrzaehlAnzproeinheit {
  ap_id: string;

  artname: string;

  ap_bearbeitung: string;

  ap_start_jahr: number;

  ap_umsetzung: string;

  ap_bearbeiter: string;

  pop_id: string;

  pop_nr: number;

  pop_name: string;

  pop_status: string;

  pop_bekannt_seit: number;

  tpop_id: string;

  tpop_nr: number;

  tpop_gemeinde: string;

  tpop_flurname: string;

  tpop_status: string;

  tpop_bekannt_seit: number;

  tpop_status_unklar: boolean;

  tpop_status_unklar_grund: string;

  tpop_x: number;

  tpop_y: number;

  tpop_radius: number;

  tpop_hoehe: number;

  tpop_exposition: string;

  tpop_klima: string;

  tpop_neigung: string;

  tpop_boden_typ: string;

  tpop_boden_kalkgehalt: string;

  tpop_boden_durchlaessigkeit: string;

  tpop_boden_humus: string;

  tpop_boden_naehrstoffgehalt: string;

  tpop_boden_abtrag: string;

  tpop_wasserhaushalt: string;

  tpop_beschreibung: string;

  tpop_kataster_nr: string;

  tpop_apber_relevant: boolean;

  tpop_apber_relevant_grund: number;

  tpop_eigentuemer: string;

  tpop_kontakt: string;

  tpop_nutzungszone: string;

  tpop_bewirtschafter: string;

  tpop_bewirtschaftung: string;

  tpop_ekfrequenz: string;

  tpop_ekfrequenz_abweichend: boolean;

  kontr_id: string;

  kontr_jahr: number;

  kontr_datum: Date;

  kontr_typ: string;

  kontr_bearbeiter: string;

  kontr_ueberlebensrate: number;

  kontr_vitalitaet: string;

  kontr_entwicklung: string;

  kontr_ursachen: string;

  kontr_erfolgsbeurteilung: string;

  kontr_umsetzung_aendern: string;

  kontr_kontrolle_aendern: string;

  kontr_bemerkungen: string;

  kontr_lr_delarze: string;

  kontr_lr_umgebung_delarze: string;

  kontr_vegetationstyp: string;

  kontr_konkurrenz: string;

  kontr_moosschicht: string;

  kontr_krautschicht: string;

  kontr_strauchschicht: string;

  kontr_baumschicht: string;

  kontr_idealbiotop_uebereinstimmung: string;

  kontr_handlungsbedarf: string;

  kontr_flaeche_ueberprueft: number;

  kontr_flaeche: number;

  kontr_plan_vorhanden: boolean;

  kontr_deckung_vegetation: number;

  kontr_deckung_nackter_boden: number;

  kontr_deckung_ap_art: number;

  kontr_jungpflanzen_vorhanden: boolean;

  kontr_vegetationshoehe_maximum: number;

  kontr_vegetationshoehe_mittel: number;

  kontr_gefaehrdung: string;

  kontr_created_at: Date;

  kontr_updated_at: Date;

  kontr_changed_by: string;

  kontr_apber_nicht_relevant: boolean;

  kontr_apber_nicht_relevant_grund: string;

  kontr_ekf_bemerkungen: string;

  id: string;

  einheit: string;

  methode: string;

  anzahl: number;
}
