// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_massn_webgisbun */
export default interface VMassnWebgisbun {
  APARTID: string;

  APART: string;

  POPGUID: string;

  POPNR: number;

  TPOPGUID: string;

  TPOPNR: number;

  TPOP_X: number;

  TPOP_Y: number;

  TPOP_WGS84LAT: number;

  TPOP_WGS84LONG: number;

  TPop_apber_relevant: boolean;

  TPop_apber_relevant_grund: string;

  TPOPSTATUS: string;

  MASSNGUID: string;

  MASSNJAHR: number;

  MASSNDAT: string;

  MASSTYP: string;

  MASSNMASSNAHME: string;

  MASSNBEARBEITER: string;

  MASSNBEMERKUNG: string;

  MASSNPLAN: boolean;

  MASSPLANBEZ: string;

  MASSNFLAECHE: number;

  MASSNFORMANSIEDL: string;

  MASSNPFLANZANORDNUNG: string;

  MASSNMARKIERUNG: string;

  MASSNANZTRIEBE: number;

  MASSNANZPFLANZEN: number;

  MASSNANZPFLANZSTELLEN: number;

  MASSNZIELEINHEITEINHEIT: string;

  MASSNZIELEINHEITANZAHL: number;

  MASSNWIRTSPFLANZEN: string;

  MASSNHERKUNFTSPOP: string;

  MASSNSAMMELDAT: string;

  MASSNVONANZAHLINDIVIDUEN: number;

  MASSNCHANGEDAT: string;

  MASSNCHANGEBY: string;
}
