// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_massn_fuergis_read */
export default interface VMassnFuergisRead {
  ap_id: string;

  artname: string;

  ap_bearbeitung: string;

  ap_start_jahr: number;

  ap_umsetzung: string;

  pop_id: string;

  pop_nr: number;

  pop_name: string;

  pop_status: string;

  pop_bekannt_seit: number;

  pop_x: number;

  pop_y: number;

  tpop_id: string;

  tpop_nr: number;

  tpop_gemeinde: string;

  tpop_flurname: string;

  tpop_status: string;

  tpop_status_unklar: boolean;

  tpop_status_unklar_grund: string;

  tpop_x: number;

  tpop_y: number;

  tpop_radius: number;

  tpop_hoehe: number;

  tpop_exposition: string;

  tpop_klima: string;

  tpop_neigung: string;

  tpop_boden_typ: string;

  tpop_boden_kalkgehalt: string;

  tpop_boden_durchlaessigkeit: string;

  tpop_boden_humus: string;

  tpop_boden_naehrstoffgehalt: string;

  tpop_boden_abtrag: string;

  tpop_wasserhaushalt: string;

  tpop_beschreibung: string;

  tpop_kataster_nr: string;

  tpop_bearbeiter: string;

  tpop_apber_relevant: boolean;

  tpop_apber_relevant_grund: number;

  tpop_bekannt_seit: number;

  tpop_eigentuemer: string;

  tpop_kontakt: string;

  tpop_nutzungszone: string;

  tpop_bewirtschafter: string;

  tpop_bewirtschaftung: string;

  massn_id: string;

  massn_jahr: number;

  massn_datum: Date;

  massn_typ: string;

  massn_beschreibung: string;

  massn_bearbeiter: string;

  massn_plan_vorhanden: boolean;

  massn_plan_bezeichnung: string;

  massn_flaeche: number;

  massn_form: string;

  massn_pflanzanordnung: string;

  massn_markierung: string;

  massn_anz_triebe: number;

  massn_anz_pflanzen: number;

  massn_anz_pflanzstellen: number;

  massn_zieleinheit_einheit: string;

  massn_zieleinheit_anzahl: number;

  massn_wirtspflanze: string;

  massn_herkunft_pop: string;

  massn_sammeldatum: string;

  massn_von_anzahl_individuen: number;

  massn_created_at: Date;

  massn_updated_at: Date;

  massn_changed_by: string;
}
