// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { PopId } from './Pop';
import type { PopmassnberId } from './Popmassnber';

/**
 * Represents the view apflora.v_popmassnber_anzmassn
 * (id) references popmassnber (id)
 */
export default interface VPopmassnberAnzmassn {
  ap_id: ApId;

  artname: string | null;

  ap_bearbeitung: string | null;

  ap_start_jahr: number | null;

  ap_umsetzung: string | null;

  pop_id: PopId;

  pop_nr: number | null;

  pop_name: string | null;

  pop_status: string | null;

  pop_bekannt_seit: number | null;

  pop_status_unklar: boolean | null;

  pop_status_unklar_begruendung: string | null;

  pop_x: number;

  pop_y: number;

  pop_created_at: Date;

  pop_updated_at: Date;

  pop_changed_by: string | null;

  id: PopmassnberId;

  jahr: number | null;

  entwicklung: string | null;

  bemerkungen: string | null;

  created_at: Date;

  updated_at: Date;

  changed_by: string | null;

  anzahl_massnahmen: string;
}
