// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the view apflora.v_pop_vonapohnestatus
 * (id) references pop (id)
 */
export default interface VPopVonapohnestatus {
  ap_id: string;

  artname: string;

  ap_bearbeitung: number;

  id: string;

  nr: number;

  name: string;

  status: number;

  x: number;

  y: number;
}
