// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { PopId } from './Pop';

/**
 * Represents the view apflora.v_pop_last_count
 * (pop_id) references pop (id)
 */
export default interface VPopLastCount {
  artname: string;

  ap_id: ApId;

  pop_id: PopId;

  pop_nr: number;

  pop_name: string;

  pop_status: string;

  jahre: string;

  'Pflanzen total': number;

  'Pflanzen (ohne Jungpflanzen)': number;

  'Triebe total': number;

  'Triebe Beweidung': number;

  Keimlinge: number;

  'davon Rosetten': number;

  Jungpflanzen: number;

  Blätter: number;

  'davon blühende Pflanzen': number;

  'davon blühende Triebe': number;

  Blüten: number;

  'Fertile Pflanzen': number;

  'fruchtende Triebe': number;

  Blütenstände: number;

  Fruchtstände: number;

  Gruppen: number;

  'Deckung (%)': number;

  'Pflanzen/5m2': number;

  'Triebe in 30 m2': number;

  'Triebe/50m2': number;

  'Triebe Mähfläche': number;

  'Fläche (m2)': number;

  Pflanzstellen: number;

  Stellen: number;

  'andere Zaehleinheit': number;

  'Art ist vorhanden': string;
}
