// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the view apflora.v_pop_anzmassn
 * (id) references pop (id)
 */
export default interface VPopAnzmassn {
  ap_id: string;

  artname: string;

  ap_bearbeitung: string;

  ap_start_jahr: number;

  ap_umsetzung: string;

  id: string;

  nr: number;

  name: string;

  status: string;

  bekannt_seit: number;

  status_unklar: boolean;

  status_unklar_begruendung: string;

  x: number;

  y: number;

  anzahl_massnahmen: string;
}
