// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_pop_fuergis_read */
export default interface VPopFuergisRead {
  ap_id: string;

  artname: string;

  ap_bearbeitung: string;

  ap_start_jahr: number;

  ap_umsetzung: string;

  id: string;

  nr: number;

  name: string;

  status: string;

  bekannt_seit: number;

  status_unklar: boolean;

  status_unklar_begruendung: string;

  x: number;

  y: number;

  created_at: Date;

  updated_at: Date;

  changed_by: string;
}
