// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_pop_fuergis_write */
export default interface VPopFuergisWrite {
  ap_id: string;

  id: string;

  nr: number;

  name: string;

  status: number;

  status_unklar: boolean;

  status_unklar_begruendung: string;

  bekannt_seit: number;

  geom_point: unknown;

  created_at: Date;

  updated_at: Date;

  changed_by: string;
}
