// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the view apflora.v_pop_kmlnamen
 * (id) references pop (id)
 */
export default interface VPopKmlnamen {
  art: string;

  label: string;

  inhalte: string;

  url: string;

  id: string;

  wgs84_lat: number;

  wgs84_long: number;
}
