// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the view apflora.v_pop_popberundmassnber
 * (pop_id) references pop (id)
 */
export default interface VPopPopberundmassnber {
  ap_id: string;

  artname: string;

  ap_bearbeitung: string;

  ap_start_jahr: number;

  ap_umsetzung: string;

  pop_id: string;

  pop_nr: number;

  pop_name: string;

  pop_status: string;

  pop_bekannt_seit: number;

  pop_status_unklar: boolean;

  pop_status_unklar_begruendung: string;

  pop_x: number;

  pop_y: number;

  pop_created_at: Date;

  pop_updated_at: Date;

  pop_changed_by: string;

  jahr: number;

  popber_id: string;

  popber_jahr: number;

  popber_entwicklung: string;

  popber_bemerkungen: string;

  popber_created_at: Date;

  popber_updated_at: Date;

  popber_changed_by: string;

  popmassnber_id: string;

  popmassnber_jahr: number;

  popmassnber_entwicklung: string;

  popmassnber_bemerkungen: string;

  popmassnber_created_at: Date;

  popmassnber_updated_at: Date;

  popmassnber_changed_by: string;
}
