// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjektId } from './Projekt';
import type { ApId } from './Ap';
import type { PopId } from './Pop';
import type { TpopId } from './Tpop';

/** Represents the view apflora.v_q_anpflanzung_zielrelevante_anzahl_falsch */
export default interface VQAnpflanzungZielrelevanteAnzahlFalsch {
  proj_id: ProjektId | null;

  ap_id: ApId;

  pop_id: PopId;

  pop_nr: number | null;

  tpop_id: TpopId;

  tpop_nr: number | null;

  id: unknown;

  jahr: unknown;

  ek_zieleinheit: unknown;

  zieleinheit_anzahl: unknown;

  anzahl: number;
}
