// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjektId } from './Projekt';
import type { ApId } from './Ap';
import type { PopId } from './Pop';
import type { TpopId } from './Tpop';
import type { TpopmassnId } from './Tpopmassn';

/** Represents the view apflora.v_q_anpflanzung_zielrelevante_einheit_falsch */
export default interface VQAnpflanzungZielrelevanteEinheitFalsch {
  proj_id: ProjektId | null;

  ap_id: ApId;

  pop_id: PopId;

  pop_nr: number | null;

  tpop_id: TpopId;

  tpop_nr: number | null;

  id: TpopmassnId;

  jahr: number | null;

  ek_zieleinheit: string | null;

  massn_zieleinheit: string | null;
}
