// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjektId } from './Projekt';
import type { ApId } from './Ap';
import type { EkzaehleinheitId } from './Ekzaehleinheit';

/** Represents the view apflora.v_q_ekzieleinheit_ohne_massn_zaehleinheit */
export default interface VQEkzieleinheitOhneMassnZaehleinheit {
  proj_id: ProjektId | null;

  ap_id: ApId;

  id: EkzaehleinheitId;

  artname: string | null;

  zaehleinheit: string | null;
}
