// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_pop_mit_ber_erloschen_ohne_tpopber_erloschen */
export default interface VQPopMitBerErloschenOhneTpopberErloschen {
  proj_id: string;

  ap_id: string;

  id: string;

  nr: number;

  berichtjahr: number;
}
