// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_pop_statuserloschenletzterpopbererloschenmitansiedlung */
export default interface VQPopStatuserloschenletzterpopbererloschenmitansiedlung {
  proj_id: string;

  ap_id: string;

  id: string;

  nr: number;
}
