// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_pop_urspruenglich_wiederauferstanden */
export default interface VQPopUrspruenglichWiederauferstanden {
  proj_id: string;

  artname: string;

  ap_id: string;

  id: string;

  nr: number;

  jahr: number;
}
