// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjektId } from './Projekt';
import type { ApId } from './Ap';
import type { PopId } from './Pop';

/** Represents the view apflora.v_q_pop_status101tpopstatusanders */
export default interface VQPopStatus101tpopstatusanders {
  proj_id: ProjektId;

  ap_id: ApId;

  id: PopId;

  nr: number | null;
}
