// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjektId } from './Projekt';
import type { ApId } from './Ap';
import type { PopId } from './Pop';

/** Represents the view apflora.v_q_pop_statuserloschenletzterpopberaktuell */
export default interface VQPopStatuserloschenletzterpopberaktuell {
  proj_id: ProjektId | null;

  ap_id: ApId | null;

  id: PopId;

  nr: number | null;
}
