// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjektId } from './Projekt';
import type { ApId } from './Ap';
import type { PopId } from './Pop';

/** Represents the view apflora.v_q_pop_mit_ber_zunehmend_ohne_tpopber_zunehmend */
export default interface VQPopMitBerZunehmendOhneTpopberZunehmend {
  proj_id: ProjektId | null;

  ap_id: ApId;

  id: PopId;

  nr: number | null;

  berichtjahr: number | null;
}
