// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_pop_koordentsprechenkeinertpop */
export default interface VQPopKoordentsprechenkeinertpop {
  proj_id: string;

  ap_id: string;

  id: string;

  nr: number;

  x: number;

  y: number;
}
