// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_pop_status201tpopstatusunzulaessig */
export default interface VQPopStatus201tpopstatusunzulaessig {
  proj_id: string;

  ap_id: string;

  nr: number;

  id: string;
}
