// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_pop_mit_ber_abnehmend_ohne_tpopber_abnehmend */
export default interface VQPopMitBerAbnehmendOhneTpopberAbnehmend {
  proj_id: string;

  ap_id: string;

  id: string;

  nr: number;

  berichtjahr: number;
}
