// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProjektId } from './Projekt';
import type { ApId } from './Ap';
import type { PopId } from './Pop';
import type { TpopId } from './Tpop';

/** Represents the view apflora.v_q_tpop_mitstatuspotentiellundzaehlungmitanzahl */
export default interface VQTpopMitstatuspotentiellundzaehlungmitanzahl {
  proj_id: ProjektId;

  ap_id: ApId | null;

  pop_id: PopId;

  pop_nr: number | null;

  id: TpopId;

  nr: number | null;
}
