// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_tpop_statuserloschenletztertpopberstabil */
export default interface VQTpopStatuserloschenletztertpopberstabil {
  proj_id: string;

  ap_id: string;

  pop_id: string;

  pop_nr: number;

  id: string;

  nr: number;
}
