// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_q_tpop_erloschen_mit_ekplan_nach_letztem_tpopber */
export default interface VQTpopErloschenMitEkplanNachLetztemTpopber {
  proj_id: string;

  ap_id: string;

  pop_id: string;

  pop_nr: number;

  id: string;

  nr: number;
}
