// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the view apflora.v_tpop_kml
 * (id) references tpop (id)
 */
export default interface VTpopKml {
  art: string;

  label: string;

  inhalte: string;

  url: string;

  id: string;

  wgs84_lat: number;

  wgs84_long: number;
}
