// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_tpop_ohneapberichtrelevant */
export default interface VTpopOhneapberichtrelevant {
  Artname: string;

  pop_nr: number;

  pop_name: string;

  id: string;

  nr: number;

  gemeinde: string;

  flurname: string;

  apber_relevant: boolean;

  apber_relevant_grund: number;

  x: number;

  y: number;
}
