// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/**
 * Represents the view apflora.v_tpop_erste_und_letzte_kontrolle_und_letzter_tpopber
 * (id) references tpop (id)
 */
export default interface VTpopErsteUndLetzteKontrolleUndLetzterTpopber {
  ap_id: string;

  familie: string;

  artname: string;

  ap_bearbeitung: string;

  ap_start_jahr: number;

  ap_umsetzung: string;

  ap_bearbeiter: string;

  pop_id: string;

  pop_nr: number;

  pop_name: string;

  pop_status: string;

  pop_bekannt_seit: number;

  pop_status_unklar: boolean;

  pop_status_unklar_begruendung: string;

  pop_x: number;

  pop_y: number;

  id: string;

  nr: number;

  gemeinde: string;

  flurname: string;

  status: number;

  status_decodiert: string;

  bekannt_seit: number;

  status_unklar: boolean;

  status_unklar_grund: string;

  x: number;

  y: number;

  radius: number;

  hoehe: number;

  exposition: string;

  klima: string;

  neigung: string;

  boden_typ: string;

  boden_kalkgehalt: string;

  boden_durchlaessigkeit: string;

  boden_humus: string;

  boden_naehrstoffgehalt: string;

  boden_abtrag: string;

  wasserhaushalt: string;

  beschreibung: string;

  kataster_nr: string;

  apber_relevant: boolean;

  apber_relevant_grund: number;

  eigentuemer: string;

  kontakt: string;

  nutzungszone: string;

  bewirtschafter: string;

  bewirtschaftung: string;

  ekfrequenz: string;

  ekfrequenz_abweichend: boolean;

  created_at: Date;

  updated_at: Date;

  changed_by: string;

  anzahl_kontrollen: string;

  letzte_kontrolle_id: string;

  letzte_kontrolle_jahr: number;

  letzte_kontrolle_datum: Date;

  letzte_kontrolle_typ: string;

  letzte_kontrolle_bearbeiter: string;

  letzte_kontrolle_ueberlebensrate: number;

  letzte_kontrolle_vitalitaet: string;

  letzte_kontrolle_entwicklung: string;

  letzte_kontrolle_ursachen: string;

  letzte_kontrolle_erfolgsbeurteilung: string;

  letzte_kontrolle_umsetzung_aendern: string;

  letzte_kontrolle_kontrolle_aendern: string;

  letzte_kontrolle_bemerkungen: string;

  letzte_kontrolle_lr_delarze: string;

  letzte_kontrolle_lr_umgebung_delarze: string;

  letzte_kontrolle_vegetationstyp: string;

  letzte_kontrolle_konkurrenz: string;

  letzte_kontrolle_moosschicht: string;

  letzte_kontrolle_krautschicht: string;

  letzte_kontrolle_strauchschicht: string;

  letzte_kontrolle_baumschicht: string;

  letzte_kontrolle_idealbiotop_uebereinstimmung: string;

  letzte_kontrolle_handlungsbedarf: string;

  letzte_kontrolle_flaeche_ueberprueft: number;

  letzte_kontrolle_flaeche: number;

  letzte_kontrolle_plan_vorhanden: boolean;

  letzte_kontrolle_deckung_vegetation: number;

  letzte_kontrolle_deckung_nackter_boden: number;

  letzte_kontrolle_deckung_ap_art: number;

  letzte_kontrolle_jungpflanzen_vorhanden: boolean;

  letzte_kontrolle_vegetationshoehe_maximum: number;

  letzte_kontrolle_vegetationshoehe_mittel: number;

  letzte_kontrolle_gefaehrdung: string;

  letzte_kontrolle_created_at: Date;

  letzte_kontrolle_updated_at: Date;

  letzte_kontrolle_changed_by: string;

  letzte_kontrolle_apber_nicht_relevant: boolean;

  letzte_kontrolle_apber_nicht_relevant_grund: string;

  letzte_kontrolle_ekf_bemerkungen: string;

  letzte_kontrolle_zaehlung_anzahlen: string;

  letzte_kontrolle_zaehlung_einheiten: string;

  letzte_kontrolle_zaehlung_methoden: string;

  erste_kontrolle_id: string;

  erste_kontrolle_jahr: number;

  erste_kontrolle_datum: Date;

  erste_kontrolle_typ: string;

  erste_kontrolle_bearbeiter: string;

  erste_kontrolle_ueberlebensrate: number;

  erste_kontrolle_vitalitaet: string;

  erste_kontrolle_entwicklung: string;

  erste_kontrolle_ursachen: string;

  erste_kontrolle_erfolgsbeurteilung: string;

  erste_kontrolle_umsetzung_aendern: string;

  erste_kontrolle_kontrolle_aendern: string;

  erste_kontrolle_bemerkungen: string;

  erste_kontrolle_lr_delarze: string;

  erste_kontrolle_lr_umgebung_delarze: string;

  erste_kontrolle_vegetationstyp: string;

  erste_kontrolle_konkurrenz: string;

  erste_kontrolle_moosschicht: string;

  erste_kontrolle_krautschicht: string;

  erste_kontrolle_strauchschicht: string;

  erste_kontrolle_baumschicht: string;

  erste_kontrolle_idealbiotop_uebereinstimmung: string;

  erste_kontrolle_handlungsbedarf: string;

  erste_kontrolle_flaeche_ueberprueft: number;

  erste_kontrolle_flaeche: number;

  erste_kontrolle_plan_vorhanden: boolean;

  erste_kontrolle_deckung_vegetation: number;

  erste_kontrolle_deckung_nackter_boden: number;

  erste_kontrolle_deckung_ap_art: number;

  erste_kontrolle_jungpflanzen_vorhanden: boolean;

  erste_kontrolle_vegetationshoehe_maximum: number;

  erste_kontrolle_vegetationshoehe_mittel: number;

  erste_kontrolle_gefaehrdung: string;

  erste_kontrolle_created_at: Date;

  erste_kontrolle_updated_at: Date;

  erste_kontrolle_changed_by: string;

  erste_kontrolle_apber_nicht_relevant: boolean;

  erste_kontrolle_apber_nicht_relevant_grund: string;

  erste_kontrolle_ekf_bemerkungen: string;

  erste_kontrolle_zaehlung_anzahlen: string;

  erste_kontrolle_zaehlung_einheiten: string;

  erste_kontrolle_zaehlung_methoden: string;

  tpopber_anz: string;

  tpopber_id: string;

  tpopber_jahr: number;

  tpopber_entwicklung: string;

  tpopber_bemerkungen: string;

  tpopber_created_at: Date;

  tpopber_updated_at: Date;

  tpopber_changed_by: string;
}
