// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { PopId } from './Pop';

/**
 * Represents the view apflora.v_tpop_last_count_with_massn
 * (tpop_id) references tpop (id)
 */
export default interface VTpopLastCountWithMassn {
  artname: string | null;

  ap_id: ApId;

  pop_nr: number | null;

  pop_name: string | null;

  pop_id: PopId;

  pop_status: string | null;

  tpop_nr: number | null;

  tpop_gemeinde: string | null;

  tpop_flurname: string | null;

  tpop_status: string | null;

  tpop_id: unknown;

  jahr: unknown;

  'Deckung X Fläche': unknown;

  'Pflanzen total': unknown;

  'Pflanzen (ohne Jungpflanzen)': unknown;

  'Triebe total': unknown;

  'Triebe Beweidung': unknown;

  Keimlinge: unknown;

  'davon Rosetten': unknown;

  Jungpflanzen: unknown;

  Blätter: unknown;

  'davon blühende Pflanzen': unknown;

  'davon blühende Triebe': unknown;

  Blüten: unknown;

  'Fertile Pflanzen': unknown;

  'fruchtende Triebe': unknown;

  Blütenstände: unknown;

  Fruchtstände: unknown;

  Gruppen: unknown;

  'Deckung (%)': unknown;

  'Pflanzen/5m2': unknown;

  'Triebe in 30 m2': unknown;

  'Triebe/50m2': unknown;

  'Triebe Mähfläche': unknown;

  'Fläche (m2)': unknown;

  Pflanzstellen: unknown;

  Stellen: unknown;

  'andere Zaehleinheit': unknown;

  'Art ist vorhanden': unknown;
}
