// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';

/** Represents the view apflora.v_tpopkontr_fuergis_read */
export default interface VTpopkontrFuergisRead {
  ap_id: ApId;

  artname: string | null;

  apherkunft: string | null;

  apjahr: number | null;

  apumsetzung: string | null;

  popid: string;

  popnr: number | null;

  popname: string | null;

  popherkunft: string | null;

  popbekanntseit: number | null;

  tpopid: string;

  tpopnr: number | null;

  tpopgemeinde: string | null;

  tpopflurname: string | null;

  tpopxkoord: number;

  tpopykoord: number;

  tpopbekanntseit: number | null;

  tpopkontrid: string;

  tpopkontrjahr: number | null;

  tpopkontrdatum: Date;

  tpopkontrtyp: string | null;

  tpopkontrbearb: string | null;

  tpopkontrueberleb: number | null;

  tpopkontrvitalitaet: string | null;

  tpopkontrentwicklung: string | null;

  tpopkontrursach: string | null;

  tpopkontrurteil: string | null;

  tpopkontraendums: string | null;

  tpopkontraendkontr: string | null;

  tpopkontrleb: string | null;

  tpopkontrflaeche: number | null;

  tpopkontrlebumg: string | null;

  tpopkontrvegtyp: string | null;

  tpopkontrkonkurrenz: string | null;

  tpopkontrmoosschicht: string | null;

  tpopkontrkrautschicht: string | null;

  tpopkontrstrauchschicht: string | null;

  tpopkontrbaumschicht: string | null;

  tpopkontridealbiotopuebereinst: string | null;

  tpopkontruebflaeche: number | null;

  tpopkontrplan: boolean | null;

  tpopkontrveg: number | null;

  tpopkontrnabo: number | null;

  tpopkontruebpfl: number | null;

  tpopkontrjungpfljn: boolean | null;

  tpopkontrveghoemax: number | null;

  tpopkontrveghoemit: number | null;

  tpopkontrgefaehrdung: string | null;

  created_at: Date;

  updated_at: Date;

  changed_by: string | null;
}
