// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TpopId } from './Tpop';

/**
 * Represents the view apflora.v_tpop_kmlnamen
 * (id) references tpop (id)
 */
export default interface VTpopKmlnamen {
  art: string | null;

  label: string;

  inhalte: string;

  url: string;

  id: TpopId;

  wgs84_lat: number;

  wgs84_long: number;
}
