// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { PopId } from './Pop';
import type { TpopId } from './Tpop';

/** Represents the view apflora.v_tpop_webgisbun */
export default interface VTpopWebgisbun {
  APARTID: ApId;

  APART: string | null;

  APSTATUS: string | null;

  APSTARTJAHR: number | null;

  APSTANDUMSETZUNG: string | null;

  POPGUID: PopId;

  POPNR: number | null;

  POPNAME: string | null;

  POPSTATUS: string | null;

  POPSTATUSUNKLAR: boolean | null;

  POPUNKLARGRUND: string | null;

  POPBEKANNTSEIT: number | null;

  POP_X: number;

  POP_Y: number;

  POP_WGS84LAT: number;

  POP_WGS84LONG: number;

  TPOPID: TpopId;

  TPOPGUID: TpopId;

  TPOPNR: number | null;

  TPOPGEMEINDE: string | null;

  TPOPFLURNAME: string | null;

  TPop_apber_relevant: boolean | null;

  TPop_apber_relevant_grund: string | null;

  TPOPSTATUS: string | null;

  TPOPSTATUSUNKLAR: boolean | null;

  TPOPUNKLARGRUND: string | null;

  TPOP_X: number;

  TPOP_Y: number;

  TPOP_WGS84LAT: number;

  TPOP_WGS84LONG: number;

  TPOPRADIUS: number | null;

  TPOPHOEHE: number | null;

  TPOPEXPOSITION: string | null;

  TPOPKLIMA: string | null;

  TPOPHANGNEIGUNG: string | null;

  TPOPBODENTYP: string | null;

  TPOPBODENKALKGEHALT: string | null;

  TPOPBODENDURCHLAESSIGKEIT: string | null;

  TPOPBODENHUMUS: string | null;

  TPOPBODENNAEHRSTOFFGEHALT: string | null;

  TPOPBODENABTRAG: string | null;

  TPOPWASSERHAUSHALT: string | null;

  TPOPBESCHREIBUNG: string | null;

  TPOPKATASTERNR: string | null;

  TPOPVERANTWORTLICH: string | null;

  TPOPBERICHTSRELEVANZ: boolean | null;

  TPOPBERICHTSRELEVANZGRUND: number | null;

  TPOPBEKANNTSEIT: number | null;

  TPOPEIGENTUEMERIN: string | null;

  TPOPKONTAKT_VO: string | null;

  TPOP_NUTZUNGSZONE: string | null;

  TPOPBEWIRTSCHAFTER: string | null;

  TPOPBEWIRTSCHAFTUNG: string | null;

  TPOPCHANGEDAT: string;

  TPOPCHANGEBY: string | null;
}
