// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { PopId } from './Pop';
import type { TpopId } from './Tpop';
import type { EkfrequenzId } from './Ekfrequenz';

/**
 * Represents the view apflora.v_tpop_anzmassn
 * (id) references tpop (id)
 */
export default interface VTpopAnzmassn {
  ap_id: ApId;

  familie: string | null;

  artname: string | null;

  ap_bearbeitung: string | null;

  ap_start_jahr: number | null;

  ap_umsetzung: string | null;

  pop_id: PopId;

  pop_nr: number | null;

  pop_name: string | null;

  pop_status: string | null;

  pop_bekannt_seit: number | null;

  pop_status_unklar: boolean | null;

  pop_status_unklar_begruendung: string | null;

  pop_x: number;

  pop_y: number;

  id: TpopId;

  nr: number | null;

  gemeinde: string | null;

  flurname: string | null;

  status: string | null;

  bekannt_seit: number | null;

  status_unklar: boolean | null;

  status_unklar_grund: string | null;

  x: number;

  y: number;

  radius: number | null;

  hoehe: number | null;

  exposition: string | null;

  klima: string | null;

  neigung: string | null;

  boden_typ: string | null;

  boden_kalkgehalt: string | null;

  boden_durchlaessigkeit: string | null;

  boden_humus: string | null;

  boden_naehrstoffgehalt: string | null;

  boden_abtrag: string | null;

  wasserhaushalt: string | null;

  beschreibung: string | null;

  kataster_nr: string | null;

  apber_relevant: boolean | null;

  apber_relevant_grund: number | null;

  eigentuemer: string | null;

  kontakt: string | null;

  nutzungszone: string | null;

  bewirtschafter: string | null;

  bewirtschaftung: string | null;

  ekfrequenz: EkfrequenzId | null;

  ekfrequenz_abweichend: boolean | null;

  anzahl_massnahmen: string;
}
