// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_tpop_popberundmassnber */
export default interface VTpopPopberundmassnber {
  ap_id: string;

  artname: string;

  ap_bearbeitung: string;

  ap_start_jahr: number;

  ap_umsetzung: string;

  pop_id: string;

  pop_nr: number;

  pop_name: string;

  pop_status: string;

  pop_bekannt_seit: number;

  pop_status_unklar: boolean;

  pop_status_unklar_begruendung: string;

  pop_x: number;

  pop_y: number;

  tpop_id: string;

  tpop_nr: number;

  tpop_gemeinde: string;

  tpop_flurname: string;

  tpop_status: string;

  tpop_bekannt_seit: number;

  tpop_status_unklar: boolean;

  tpop_status_unklar_grund: string;

  tpop_x: number;

  tpop_y: number;

  tpop_radius: number;

  tpop_hoehe: number;

  tpop_exposition: string;

  tpop_klima: string;

  tpop_neigung: string;

  tpop_boden_typ: string;

  tpop_boden_kalkgehalt: string;

  tpop_boden_durchlaessigkeit: string;

  tpop_boden_humus: string;

  tpop_boden_naehrstoffgehalt: string;

  tpop_boden_abtrag: string;

  tpop_wasserhaushalt: string;

  tpop_beschreibung: string;

  tpop_kataster_nr: string;

  tpop_apber_relevant: boolean;

  tpop_apber_relevant_grund: number;

  tpop_eigentuemer: string;

  tpop_kontakt: string;

  tpop_nutzungszone: string;

  tpop_bewirtschafter: string;

  tpop_bewirtschaftung: string;

  tpop_ekfrequenz: string;

  tpop_ekfrequenz_abweichend: boolean;

  tpopber_id: string;

  tpopber_jahr: number;

  tpopber_entwicklung: string;

  tpopber_bemerkungen: string;

  tpopber_created_at: Date;

  tpopber_updated_at: Date;

  tpopber_changed_by: string;

  tpopmassnber_id: string;

  tpopmassnber_jahr: number;

  tpopmassnber_entwicklung: string;

  tpopmassnber_bemerkungen: string;

  tpopmassnber_created_at: Date;

  tpopmassnber_updated_at: Date;

  tpopmassnber_changed_by: string;
}
