// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_tpop_ohnebekanntseit */
export default interface VTpopOhnebekanntseit {
  artname: string;

  ap_bearbeitung: string;

  pop_nr: number;

  pop_name: string;

  nr: number;

  gemeinde: string;

  flurname: string;

  bekannt_seit: number;

  id: string;

  x: number;

  y: number;
}
