// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_tpop_statuswidersprichtbericht */
export default interface VTpopStatuswidersprichtbericht {
  Art: string | null;

  'Bearbeitungsstand AP': string | null;

  pop_nr: number | null;

  pop_name: string | null;

  nr: number | null;

  gemeinde: string | null;

  flurname: string | null;

  status: number | null;

  TPopBerEntwicklung: number | null;

  tpopber_jahr: number | null;
}
