// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AdresseId } from './Adresse';

/** Represents the view apflora.v_tpopkontr_fuergis_write */
export default interface VTpopkontrFuergisWrite {
  id: string;

  typ: string | null;

  jahr: number | null;

  datum: Date;

  bearbeiter: AdresseId | null;

  ueberlebensrate: number | null;

  entwicklung: number | null;

  vitalitaet: string | null;

  ursachen: string | null;

  erfolgsbeurteilung: string | null;

  umsetzung_aendern: string | null;

  kontrolle_aendern: string | null;

  lr_delarze: string | null;

  flaeche: number | null;

  lr_umgebung_delarze: string | null;

  vegetationstyp: string | null;

  konkurrenz: string | null;

  moosschicht: string | null;

  krautschicht: string | null;

  strauchschicht: string | null;

  baumschicht: string | null;

  idealbiotop_uebereinstimmung: number | null;

  flaeche_ueberprueft: number | null;

  plan_vorhanden: boolean | null;

  deckung_vegetation: number | null;

  deckung_nackter_boden: number | null;

  deckung_ap_art: number | null;

  jungpflanzen_vorhanden: boolean | null;

  vegetationshoehe_maximum: number | null;

  vegetationshoehe_mittel: number | null;

  gefaehrdung: string | null;

  bemerkungen: string | null;

  created_at: Date;

  updated_at: Date;

  changed_by: string | null;
}
