// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_tpop_ekfrequenz_to_set_nie */
export default interface VTpopEkfrequenzToSetNie {
  artname: string;

  pop_nr: number;

  id: string;

  nr: number;

  status_code: number;

  status_text: string;

  status_code_2019: number;

  status_text_2019: string;

  ekfrequenz_id: string;

  ekfrequenz_code: string;

  ekfrequenz_to_set_id: string;

  ekfrequenz_to_set_code: string;
}
