// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ApId } from './Ap';
import type { PopId } from './Pop';
import type { TpopId } from './Tpop';
import type { TpopkontrId } from './Tpopkontr';

/** Represents the view apflora.v_tpopkontr_webgisbun */
export default interface VTpopkontrWebgisbun {
  APARTID: ApId;

  APART: string | null;

  POPGUID: PopId;

  POPNR: number | null;

  TPOPGUID: TpopId;

  TPOPNR: number | null;

  TPop_apber_relevant: boolean | null;

  TPop_apber_relevant_grund: string | null;

  KONTRGUID: TpopkontrId;

  KONTRJAHR: number | null;

  KONTRDAT: string;

  KONTRTYP: string | null;

  TPOPSTATUS: string | null;

  KONTRBEARBEITER: string | null;

  KONTRUEBERLEBENSRATE: number | null;

  KONTRVITALITAET: string | null;

  KONTRENTWICKLUNG: string | null;

  KONTRURSACHEN: string | null;

  KONTRERFOLGBEURTEIL: string | null;

  KONTRAENDUMSETZUNG: string | null;

  KONTRAENDKONTROLLE: string | null;

  KONTR_X: number;

  KONTR_Y: number;

  KONTR_WGS84LAT: number;

  KONTR_WGS84LONG: number;

  KONTRBEMERKUNGEN: string | null;

  KONTRLRMDELARZE: string | null;

  KONTRDELARZEANGRENZ: string | null;

  KONTRVEGTYP: string | null;

  KONTRKONKURRENZ: string | null;

  KONTRMOOSE: string | null;

  KONTRKRAUTSCHICHT: string | null;

  KONTRSTRAUCHSCHICHT: string | null;

  KONTRBAUMSCHICHT: string | null;

  KONTRUEBEREINSTIMMUNIDEAL: string | null;

  KONTRHANDLUNGSBEDARF: string | null;

  KONTRUEBERPRUFTFLAECHE: number | null;

  KONTRFLAECHETPOP: number | null;

  KONTRAUFPLAN: boolean | null;

  KONTRDECKUNGVEG: number | null;

  KONTRDECKUNGBODEN: number | null;

  KONTRDECKUNGART: number | null;

  KONTRJUNGEPLANZEN: boolean | null;

  KONTRMAXHOEHEVEG: number | null;

  KONTRMITTELHOEHEVEG: number | null;

  KONTRGEFAEHRDUNG: string | null;

  KONTRCHANGEDAT: string;

  KONTRCHANGEBY: string | null;

  ZAEHLEINHEITEN: string;

  ANZAHLEN: string;

  METHODEN: string;
}
