// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the view apflora.v_tpop_fuergis_write */
export default interface VTpopFuergisWrite {
  pop_id: string;

  tpop_id: string;

  tpop_nr: number | null;

  tpop_gemeinde: string | null;

  tpop_flurname: string | null;

  tpop_status: number | null;

  tpop_status_unklar: boolean | null;

  tpop_status_unklar_grund: string | null;

  tpop_x: number;

  tpop_y: number;

  tpop_radius: number | null;

  tpop_hoehe: number | null;

  tpop_exposition: string | null;

  tpop_klima: string | null;

  tpop_neigung: string | null;

  tpop_boden_typ: string | null;

  tpop_boden_kalkgehalt: string | null;

  tpop_boden_durchlaessigkeit: string | null;

  tpop_boden_humus: string | null;

  tpop_boden_naehrstoffgehalt: string | null;

  tpop_boden_abtrag: string | null;

  tpop_wasserhaushalt: string | null;

  tpop_beschreibung: string | null;

  tpop_kataster_nr: string | null;

  tpop_apber_relevant: boolean | null;

  tpop_apber_relevant_grund: number | null;

  tpop_bekannt_seit: number | null;

  tpop_eigentuemer: string | null;

  tpop_kontakt: string | null;

  tpop_nutzungszone: string | null;

  tpop_bewirtschafter: string | null;

  tpop_bewirtschaftung: string | null;

  tpop_bemerkungen: string | null;

  tpop_created_at: Date;

  tpop_updated_at: Date;

  tpop_changed_by: string | null;
}
