// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for apflora.ziel_typ_werte */
export type ZielTypWerteId = string & { __brand: 'apflora.ziel_typ_werte' };

/** Represents the table apflora.ziel_typ_werte */
export default interface ZielTypWerte {
  /** Primärschlüssel */
  id: ZielTypWerteId;

  code: number | null;

  /** Beschreibung des Ziels */
  text: string | null;

  sort: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic: boolean | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table apflora.ziel_typ_werte */
export interface ZielTypWerteInitializer {
  /**
   * Primärschlüssel
   * Default value: uuid_generate_v1mc()
   */
  id?: ZielTypWerteId;

  /** Default value: nextval('apflora.ziel_typ_werte_code_seq'::regclass) */
  code?: number | null;

  /**
   * Beschreibung des Ziels
   * Default value: NULL::character varying
   */
  text?: string | null;

  sort?: number | null;

  /**
   * Von wem wurde der Datensatz zuletzt geändert?
   * Default value: NULL::character varying
   */
  changed_by?: string | null;

  /**
   * Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten
   * Default value: false
   */
  historic?: boolean | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table apflora.ziel_typ_werte */
export interface ZielTypWerteMutator {
  /** Primärschlüssel */
  id?: ZielTypWerteId;

  code?: number | null;

  /** Beschreibung des Ziels */
  text?: string | null;

  sort?: number | null;

  /** Von wem wurde der Datensatz zuletzt geändert? */
  changed_by?: string | null;

  /** Wert wird nur angezeigt, wenn er in den Daten (noch) enthalten ist. Wird in Auswahl-Listen nicht mehr angeboten */
  historic?: boolean | null;

  created_at?: Date;

  updated_at?: Date;
}
