// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface algorithm_sign_params {
  signables: string;

  secret: string;

  algorithm: string;
}

/** Return type for algorithm_sign */
export type algorithm_sign_return_type = string;
