// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the compositeType auth.jwt_token */
export default interface JwtToken {
  role: string | null;

  username: string | null;

  token: string | null;
}
