// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface sign_params {
  payload: unknown;

  secret: string;

  algorithm: string;
}

/** Return type for sign */
export type sign_return_type = string;
