// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface url_encode_params {
  data: unknown;
}

/** Return type for url_encode */
export type url_encode_return_type = string;
