// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface verify_params {
  token: string;

  secret: string;

  algorithm: string;

  header: unknown;

  payload: unknown;

  valid: boolean;
}

/** Return type for verify */
export interface verify_return_type {
  header: unknown;

  payload: unknown;

  valid: boolean;
}
