// @flow
import { types } from 'mobx-state-tree'

export const type = types.model({
  nr: types.optional(types.maybeNull(types.number), null),
  gemeinde: types.optional(types.maybeNull(types.string), null),
  flurname: types.optional(types.maybeNull(types.string), null),
  x: types.optional(types.maybeNull(types.number), null),
  y: types.optional(types.maybeNull(types.number), null),
  radius: types.optional(types.maybeNull(types.number), null),
  hoehe: types.optional(types.maybeNull(types.number), null),
  exposition: types.optional(types.maybeNull(types.string), null),
  klima: types.optional(types.maybeNull(types.string), null),
  neigung: types.optional(types.maybeNull(types.string), null),
  beschreibung: types.optional(types.maybeNull(types.string), null),
  katasterNr: types.optional(types.maybeNull(types.string), null),
  status: types.optional(types.maybeNull(types.number), null),
  statusUnklar: types.optional(types.maybeNull(types.boolean), null),
  statusUnklarGrund: types.optional(types.maybeNull(types.string), null),
  apberRelevant: types.optional(types.maybeNull(types.number), null),
  bekanntSeit: types.optional(types.maybeNull(types.number), null),
  eigentuemer: types.optional(types.maybeNull(types.string), null),
  kontakt: types.optional(types.maybeNull(types.string), null),
  nutzungszone: types.optional(types.maybeNull(types.string), null),
  bewirtschafter: types.optional(types.maybeNull(types.string), null),
  bewirtschaftung: types.optional(types.maybeNull(types.string), null),
  kontrollfrequenz: types.optional(types.maybeNull(types.number), null),
  kontrollfrequenzFreiwillige: types.optional(
    types.maybeNull(types.number),
    null,
  ),
  bemerkungen: types.optional(types.maybeNull(types.string), null),
})

export const initial = {
  nr: null,
  gemeinde: null,
  flurname: null,
  x: null,
  y: null,
  radius: null,
  hoehe: null,
  exposition: null,
  klima: null,
  neigung: null,
  beschreibung: null,
  katasterNr: null,
  status: null,
  statusUnklar: null,
  statusUnklarGrund: null,
  apberRelevant: null,
  bekanntSeit: null,
  eigentuemer: null,
  kontakt: null,
  nutzungszone: null,
  bewirtschafter: null,
  bewirtschaftung: null,
  kontrollfrequenz: null,
  kontrollfrequenzFreiwillige: null,
  bemerkungen: null,
}

export const simpleTypes = {
  nr: 'number',
  gemeinde: 'string',
  flurname: 'string',
  x: 'number',
  y: 'number',
  radius: 'number',
  hoehe: 'number',
  exposition: 'string',
  klima: 'string',
  neigung: 'string',
  beschreibung: 'string',
  katasterNr: 'string',
  status: 'number',
  statusUnklar: 'boolean',
  statusUnklarGrund: 'string',
  apberRelevant: 'number',
  bekanntSeit: 'number',
  eigentuemer: 'string',
  kontakt: 'string',
  nutzungszone: 'string',
  bewirtschafter: 'string',
  bewirtschaftung: 'string',
  kontrollfrequenz: 'number',
  kontrollfrequenzFreiwillige: 'number',
  bemerkungen: 'string',
}
